### PR TITLE
Fix fetching language from DAV attendee

### LINKED ISSUE #3414: Get participant language and save it, so that invitation emails are sent with the correct language
### Steps

1. Have two users Alice and Bob
2. Login as "Alice"
3. Set the language to French "fr_FR" in the personal setting
4. Create a calendar event
5. Go to participants
6. Add user "Bob" as participant
7. Save the event
8. Check email for Bob

### Expected result
Email received by Bob is in English.

### Actual result
Email received by Bob is in French.

### Version
The one on c.nc.com

### PR DESCRIPTION
**Pull request by tcitworld**
Closes #3414

* [x] Requires https://github.com/nextcloud/server/pull/28458 in server
* [x] Requires `npm link` to https://github.com/nextcloud/cdav-library/pull/534 via #3423

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by ChristophWurst** [comment]
marked as draft so we don't accidentally merge before the server change

**Comment by tcitworld** [comment]
Well this change doesn't require either PR to be merged, only to work correctly and fix the issue. :)

**Review by st3iny — APPROVED** [review]
I tested all three PRs together and it works well.

**Comment by ChristophWurst** [comment]
> I tested all three PRs together and it works well.

Please approve https://github.com/nextcloud/server/pull/28458 :)

**Comment by st3iny** [comment]
@ChristophWurst I tested this without the linked PRs and nothing broke. I think we can just merge it without any version checks or waiting for the upstream PR.

**Pull request merged**
