### PR TITLE
Sticky save buttons

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/calendar/issues/1960

| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
Anyone knows why the compile bot fails?

**Comment by st3iny** [comment]
> Anyone knows why the compile bot fails?

We don't need it here in calendar. The artifacts are not stored in the git repository but are compiled on the fly prior to releasing it.

**Comment by tcitworld** [comment]
If we do that I'd like a little height margin on the button so that it's harder to misclick between selecting a field and clicking the button.

**Comment by GretaD** [comment]
> If we do that I'd like a little height margin on the button so that it's harder to misclick between selecting a field and clicking the button.

we can add `height=44px; `as thats the default one.

**Review by GretaD — APPROVED** [review]
approved so it doesnt get blocked, please see comment about height

**Comment by szaimen** [comment]
> If we do that I'd like a little height margin on the button so that it's harder to misclick between selecting a field and clicking the button.

done, see updated screenshots

**Comment by alexanderdd** [comment]
I might be too late: what does it look like on a existing event (not new one)?

Because if we make the save button always visible (yeah!), shouldn't the delete button be right next to it and also always visible?

**Comment by tcitworld** [comment]
@alexanderdd That's not in the scope of this PR but you might be interested in https://github.com/nextcloud/calendar/issues/2893

**Pull request merged**
