### PR TITLE
Improve appointments overview page

### LINKED ISSUE #3623: Use buttons for appointment configs on the overview page
Make the appointment as a button with the grey area. It would be nice to have boxes around the appointment like in dashboard.

### LINKED ISSUE #3642: Improve text on appointment overview page
The user name should be in bold and `h2` and appointment names shouldn't be in bold. Add text "Book an appointment with {{name}}" between the avatar and the appointment slots.

### LINKED ISSUE #3644: Replace arrow with event icon on the appointment overview page

### PR DESCRIPTION
**Pull request by st3iny**
Fix #3623 
Fix #3642
Fix #3644 

## Screenshots

Screenshot 2021-11-12 at 17-48-12 Nextcloud

Screenshot 2021-11-12 at 17-22-23 Nextcloud

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Two remarks
* Can we include the length? I think this is quite insightful and makes the slots more distinguishable
* Can we show (the first few words) of the description? @GretaD we had that in the design review but I don't fully recall how it should look like. Was that the point where we then said the appointment configs should each render like a widget of the dashboard?

**Comment by ChristophWurst** [comment]
Attempt of a mockup

Bildschirmfoto von 2021-11-12 15-29-31

Time time (e.g. *2 hours*) could show underneath the config title

**Comment by GretaD** [comment]
> * Can we show (the first few words) of the description? @GretaD we had that in the design review but I don't fully recall how it should look like. Was that the point where we then said the appointment configs should each render like a widget of the dashboard?

Yes, it should look like/similar to dashboard(when you click customize). Also, the name should go and instead we should only have "Book an appointment with {{name}}.

**Comment by ChristophWurst** [comment]
> Also, the name should go and instead we should only have "Book an appointment with {{name}}.

Are you sure? We already show that text above the configs.

I'm talking about how each of the configs is shown.

**Comment by GretaD** [comment]
> > Also, the name should go and instead we should only have "Book an appointment with {{name}}.
> 
> Are you sure? We already show that text above the configs.
> 
> I'm talking about how each of the configs is shown.

On my notes I have written: _The name should be a h2. Combine the name and the booking. "Book an appoitment with {{name}}"_

**Comment by GretaD** [comment]
> I'm talking about how each of the configs is shown.

From notes: _Make the appointment as a button with the grey area. It would be nice to have boxes around the appoitment like in dashboard. Lets remove the arrow on the right, we use the event icon on all of them._

**Comment by ChristophWurst** [comment]
Bildschirmfoto von 2021-11-12 15-36-54

so like that?

**Comment by GretaD** [comment]
> Bildschirmfoto von 2021-11-12 15-36-54
> 
> so like that?

yes, thats what I would do reading the notes

**Comment by st3iny** [comment]
Thanks for your feedback. Now it is clear how it should look. One minor thing though: Should the calendar icon be inline with the config name or above (like in the second mockup)?

**Comment by GretaD** [comment]
> Thanks for your feedback. Now it is clear how it should look. One minor thing though: Should the calendar icon be inline with the config name or above (like in the second mockup)?

we didnt discuss anything about this, so do it like you think looks better

**Comment by st3iny** [comment]
I implemented the feedback and updated all screenshots.

**Review by GretaD — APPROVED** [review]

**Pull request merged**
