### PR TITLE
Release/1.6.5

### PR DESCRIPTION
**Pull request by georgehrke**

### CODE REVIEW

**Comment by tcitworld** [comment]
I didn't my changes with NC 14, not sure it's 100% CSS variable safe.

**Comment by tcitworld** [comment]
Yup, `var(--border-radius-pill)` is undefined on NC 14. Any clue other that to go back to SCSS here @skjnldsv ?

Capture d’écran du 2019-04-08 10-13-23

**Comment by skjnldsv** [comment]
@tcitworld you need to check the history of https://github.com/nextcloud/server/blob/master/core/css/css-variables.scss :)

**Comment by tcitworld** [comment]
Added the raw value for NC14 support.

@georgehrke Ready to release.

**Comment by georgehrke** [comment]
@tcitworld Did you test this in 14 and 15? :)

**Comment by tcitworld** [comment]
Tested in 15 when developed, then 14 with the above fix.

**Comment by tcitworld** [comment]
(only my changes, not the rest)

**Comment by georgehrke** [comment]
👍

**Comment by georgehrke** [comment]
published

**Pull request merged**
