### PR TITLE
chore: vendor closest-css-color and its dependencies

### PR DESCRIPTION
**Pull request by st3iny**
I vendored the code of `closest-css-color` and `colour-proximity`. I had to refactor/modernize the code a bit to make it compliant with our eslint rules. I also adopted and translated the test suite of `closest-css-color`

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by tcitworld** [comment]
No mention of the original licence?

**Comment by st3iny** [comment]
> No mention of the original licence?

Hmm, you are probably right.

- `colour-proximity` has no license. 
- `closest-css-color` is licensed via ISC

Ref https://github.com/nextcloud/calendar/pull/5007

**Pull request merged**
