### PR TITLE
add workaround to fix webcal creation under Nextcloud9

### PR DESCRIPTION
**Pull request by georgehrke**
Nextcloud9 has a bug, that it doesn't save color, enabled and displayname when sending a MKCOL for a subscription.
This patch mitigates the issue by sending an additional update request when running on Nextcloud 9.

### CODE REVIEW

**Comment by georgehrke** [comment]
decreased coverage is fine for now. There are no tests for the calendar service yet.

**Comment by georgehrke** [comment]
What do you think @tcitworld @raghunayyar? :)

**Comment by tcitworld** [comment]
Maybe we can send the fix to server too ?

**Comment by georgehrke** [comment]
I'm not sure if it's going to be back ported. And I want to get 1.4.0 out by today :)

**Comment by georgehrke** [comment]
It's already fixed in Nextcloud 10 and master

**Comment by georgehrke** [comment]
So is this ok with you to merge? :)

**Comment by tcitworld** [comment]
:+1: Needs rebase.

**Pull request merged**
