### PR TITLE
Keyboard shortcut for List View

### PR DESCRIPTION
**Pull request by louismarkert**
Adding a Keyboard shortcut for the List View.

There is still the need for adding the Shortcuts Description to all the different translations.

This closes Issue #2717.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
FYI translations are added via Transifex and a bot

**Comment by louismarkert** [comment]
Tested it on my server now, everything seems to work as intended.

**Review by ChristophWurst — APPROVED** [review]

**Comment by louismarkert** [comment]
Thank you @ChristophWurst for the friendly and smooth experience on my first small open source contribution :)

**Comment by ChristophWurst** [comment]
Congrats and welcome to open source :)

**Pull request merged**
