### PR TITLE
Release 2.0.0 RC

### PR DESCRIPTION
**Pull request by georgehrke**
Signed-off-by: Georg Ehrke <developer@georgehrke.com>

### CODE REVIEW

**Comment by tcitworld** [comment]
> Release RC only on 18 

Are there some things that prevent having 17 compatibility for final version?

**Comment by georgehrke** [comment]
> Are there some things that prevent having 17 compatibility for final version?

I haven't tested it properly to be honest. All my instances are already running on 18 RC. I wanted to publish this RC on the appstore, that's why i set it to 18 for now.

**Comment by georgehrke** [comment]
Let me actually remove it and create a special PR for the appstore build.
Then we don't break master

**Comment by tcitworld** [comment]
> Let me actually remove it and create a special PR for the appstore build. Then we don't break master

:+1:

**Pull request merged**
