### PR TITLE
Updated changes in public.scss

### PR DESCRIPTION
**Pull request by SakshiT25**
Fixes https://github.com/nextcloud/calendar/issues/4715

Continuation of https://github.com/nextcloud/calendar/pull/4779

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Please link the ticket this pull request addresses

**Review by st3iny — APPROVED** [review]
Tested and works. Thank you very much!

Please squash all commits into one and we are ready to merge.

**Comment by SakshiT25** [comment]
> Tested and works. Thank you very much!
> 
> Please squash all commits into one and we are ready to merge.

Thanks for your feedback. Please let me know if the squashing needs to be done from my end as I'm currently facing the write access error.

**Comment by st3iny** [comment]
I wanted to squash your commits and accidentally deleted your remote branch. I'm very sorry.

I still have the changes locally and pushed your changes to https://github.com/nextcloud/calendar/pull/4807.

**Pull request closed without merging**
