### PR TITLE
fix settings design regression

### PR DESCRIPTION
**Pull request by szaimen**
| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by tcitworld** [comment]
That's a quick fix but it would be better if the lines too long would wrap.

**Comment by szaimen** [comment]
> That's a quick fix but it would be better if the lines too long would wrap.

Yes, but I'd suggest doing that in a follow up since this issue is much worse than lines not wrapping, imho.

**Comment by tcitworld** [comment]
The proper fix would be https://github.com/nextcloud/calendar/pull/3041 :smirk:

**Comment by szaimen** [comment]
> The proper fix would be #3041 😏

Yes, but can we bring it this small fix until the mentioned PR is merged?

**Review by tcitworld — APPROVED** [review]

**Comment by szaimen** [comment]
Thanks!

**Comment by GretaD** [comment]
this is not a regression, but something done on purpose, have a look here: https://github.com/nextcloud/calendar/pull/3026#issuecomment-821099937

**Comment by szaimen** [comment]
Okay, then revert?

**Comment by GretaD** [comment]
@tcitworld  @raimund-schluessler, what do you think?

The thing is that im working on our roudmap now, and I havent found the time to check the modal out, so i dont know when that is going to be done

**Comment by szaimen** [comment]
Btw: if we should decide to leave it this way, we should also merge the still pending backport:
https://github.com/nextcloud/calendar/pull/3345

**Comment by raimund-schluessler** [comment]
I would tend to keep it, since `overflow: visible` also makes the whole calendar grid moving to the top, which indeed looks broken. The increased difficulty selecting a timezone is not so critical I think. But I can live with either decision.

**Comment by GretaD** [comment]
Cool, i also think the same as i already shoot a fixup some time ago :)

**Pull request merged**
