### PR TITLE
Allow a calendar to be shared with circles.

### PR DESCRIPTION
**Pull request by viniciuscb**
The possibility to share a calendar with a circle is implemented in this commit and in commit e534c55 in nextcloud core.

There is a PR there: 
https://github.com/nextcloud/server/pull/6512

I've tested this functionality using nextcloud 12.

### CODE REVIEW

**Comment by viniciuscb** [comment]
@dtygel

**Comment by georgehrke** [comment]
please review @daita

**Comment by georgehrke** [comment]
Hey :)

Thx for your pull-request!
I cc'ed @daita who develops the circle app.

Can you please look into the failing unit tests?

**Comment by georgehrke** [comment]
@daita @viniciuscb What's the status on this? :)

**Comment by daita** [comment]
Looks like it works, having some GUI issue:

selection_087

but it works

**Comment by daita** [comment]
Remember that this will needs nextcloud/server#6512

**Comment by viniciuscb** [comment]
Hi @daita , progress in this review? What should I do to have this accepted?

**Comment by wargreen** [comment]
hi,
Is it some news or WIP about this feature, or is it delayed to NC14 ?

**Comment by tcitworld** [comment]
It is since it needs some server changes.

**Comment by GoetheG** [comment]
Hey guys. Really great that you are working on that! Really looking forward to seeing your progress soon. Your contribution is one more step towards a real collaboration platform.

Cheers

**Comment by GoetheG** [comment]
.

**Comment by jmcclelland** [comment]
Is there any update on this issue? Using circles with calendar would be a really useful feature.

**Comment by dtygel** [comment]
> Is there any update on this issue? Using circles with calendar would be a really useful feature.

We've been using this feature for more than a year in our NC implementation, already in NC14. Here, we're waiting for a review and guidelines to make it acceptable to be merged.

**Comment by georgehrke** [comment]
@dtygel Did you apply any changes to nextcloud/server#6512 or are you just using it like that?

**Comment by viniciuscb** [comment]
Hi @georgehrke we had to do some small changes when upgrading to nextcloud 14. I can make a review of this code to see if it works / which modifications are needed to work in the last version of nextcloud. Should I test it working /do the modifications to work in branch master?

**Comment by viniciuscb** [comment]
Using like that. Made a cherry-pick from previous commit and it worked in master. Made a new commit with current date and a more precise description. This and PR nextcloud/server#6512 were enough to allow a calendar to be shared with a circle.

**Comment by daita** [comment]
@georgehrke so, we will need a release of Calendar for NC16 including this PR. nextcloud/server#12119 will be merge also.

**Comment by MorrisJobke** [comment]
@skjnldsv Mind to review this and release a new version of the app?

**Comment by georgehrke** [comment]
@MorrisJobke I will review and release this weekend

**Comment by georgehrke** [comment]
Works very well.

@viniciuscb Thank you for this pull-request. I'm happy to finally get this in. 
I'm sorry it took so long.

**Comment by GoetheG** [comment]
Is this issue still open?

**Pull request merged**
