### PR TITLE
Calendar 2.0.0 beta1

### PR DESCRIPTION
**Pull request by georgehrke**
Signed-off-by: Georg Ehrke <developer@georgehrke.com>

### CODE REVIEW

**Comment by tcitworld** [comment]
It would be nice if we also added an introduction paragraph explaining the migration to Vue.

**Comment by georgehrke** [comment]
Missing in Changelog: 
- #748

**Comment by georgehrke** [comment]
> It would be nice if we also added an introduction paragraph explaining the migration to Vue.

Definitely! Do you want to look into that? :)

**Comment by tcitworld** [comment]
> Version 2.0 of the calendar has been fully rewritten with a different technology, switching from the legacy AngularJS framework to [Vue.js](https://vuejs.org/). Nextcloud is using more and more Vue.js throughout apps and server, which makes it easy to use [common components](https://nextcloud-vue-components.netlify.com/) everywhere. This allows faster development and a more coherent experience in all of Nextcloud.

> Even though all features present on the 1.x calendar app versions have been reimplemented, new bugs might have been introduced. Please report them if you find some.

**Pull request merged**
