### PR TITLE
Move calendar sharing and settings to a modal

### LINKED ISSUE #4124: Redesign calendar sharing
### Is your feature request related to a problem? Please describe.

Calendar sharing is currently a bit problematic from a usability and accessibility point of view, so it was added to https://github.com/nextcloud/calendar/issues/3540.

### Describe the solution you'd like

> "can edit" is difficult to uncheck with keyboard, as the focus switches somehow after checking it

To be defined by designers.

### Describe alternatives you've considered

To be defined by designers.

### Additional context

_No response_

### LINKED ISSUE #4711: Improve usability of colour picker
### Is your feature request related to a problem? Please describe.

Currently, changing the calendar colour is cumbersome and unintuitive.

I have to click three times to change the calendar colour.

image

### Describe the solution you'd like

Auto save the colour as soon as it is picked and remove the unintuitive right arrow from the colour field.

### Describe alternatives you've considered

use the NC ue colour picker
https://nextcloud-vue-components.netlify.app/#/Components/NcPickers?id=nccolorpicker

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by st3iny**
Fix #4124  
Fix #4711 

**WIP**

## First iteration

| Calendar list item | Modal |
| --- | --- |
| image | image |

## Second iteration

There is no three dot menu anymore in the calendar list. There will be a single pencil icon/button which opens the modal.

image

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Are the broken avatars spreading? :see_no_evil: I thought only attendees look broken, not sharees.

**Comment by st3iny** [comment]
> Are the broken avatars spreading? see_no_evil I thought only attendees look broken, not sharees.

They are working when initially adding the sharee. After a page load they break :thinking: I'm still investigating if my migration might have broken them.

**Comment by st3iny** [comment]
> Are the broken avatars spreading? see_no_evil I thought only attendees look broken, not sharees.

I fixed it.

**Comment by st3iny** [comment]
> I assume it is because still WIP, but will the rest of the dropdown also be moved into the modal? :) Basically clicking the 3 dot icon should open the modal, and all info of the dropdown should be in the modal.
> 
> > What seems most fitting is if we put "Calendar details & sharing" into a modal together, so name, color, and sharing can be edited in one place. Export and Delete calendar can be done there as well, basically just like the "Conversation settings" in Talk.

I kept them in a list for quick access. A unified design makes more sense. I'll move all other buttons to the modal too.

**Comment by ChristophWurst** [comment]
> I assume it is because still WIP, but will the rest of the dropdown also be moved into the modal? :) Basically clicking the 3 dot icon should open the modal, and all info of the dropdown should be in the modal.

Could you please spec how this should look?

Bildschirmfoto vom 2022-11-18 17-12-19

**Comment by ChristophWurst** [comment]
Looks super nice now @st3iny!

Should we move the *Delete* button to the bottom though? In other menus we also always put it last.

Bildschirmfoto vom 2022-11-18 17-23-43

**Comment by ChristophWurst** [comment]
@GretaD could you please move the buttons to the bottom of the modal?

**Comment by GretaD** [comment]
Screenshot from 2022-11-22 14-50-52

**Review by ChristophWurst — APPROVED** [review]
:sunglasses:

**Pull request merged**
