### PR TITLE
Reduce brightness of events

### PR DESCRIPTION
**Pull request by georgehrke**
| Before | After |
|:---------:|:------:|
|before|after|

please review and test @nextcloud/designers

At the last Calendar Design review session, we discussed whether we should reduce the brightness of events in the calendar-grid.

| Before | After |
|:---------:|:------:|
|10%|after-0-1|
|20%|after-0-2|
|30%|after-0-3|

### CODE REVIEW

**Comment by georgehrke** [comment]
Maybe 10% alpha is too low.

**Comment by SuperSandro2000** [comment]
I am not a designer by any means but the news designs makes the colors really hard to guess.

**Comment by georgehrke** [comment]
I added some screenshots of different alpha values to the original post

**Comment by nrgeen** [comment]
30% looks very good for me

**Comment by skjnldsv** [comment]
Maybe check against WCAG ?

**Review by ma12-co — COMMENTED** [review]
@georgehrke, could we see a screenshot with opacity 30% and bold event titles?

**Comment by tcitworld** [comment]
I need to have look at how it looks in dark mode, but "outlined" events are quite nice around 30% opacity.

**Comment by georgehrke** [comment]
@ma12-co @tcitworld Here you go: 0.3 with bold font in light and dark:

| Light | Dark|
|:---------:|:------:|
|month_light|month_dark|

**Comment by ma12-co** [comment]
Looks very nice to me :) 
One more thing, what's the margin between events? 2px? seems a little tight to me

**Comment by georgehrke** [comment]
> Maybe check against WCAG ?

Only for 0.1 I'm getting a contract ratio of 4.74, which is good enough to pass `AA`, but not `AAA`.

Setting the alpha value of the background to 1.5, 2, 2.5, or 3 gives a contrast ratio of less than 4.5

**Comment by ma12-co** [comment]
I guess we have to use 0.1 then. Another thing we could do would be darkening the events colors, that should also help.

**Comment by jancborchardt** [comment]
My worry about using such low opacity is like @SuperSandro2000 said:

> the new designs make the colors really hard to guess for me.

And the borders on all the events make it look a bit much to take in, lots of boxes and lines. 2 big approaches are:
- Full color boxes like Google Calendar
- Light boxes without border, like macOS Calendar

**Comment by ChristophWurst** [comment]
Is there anything left to do? Otherwise I can try to rebase, give a smoke test and integrate :)

**Comment by szaimen** [comment]
not needed anymore

**Pull request closed without merging**
