### PR TITLE
Disable publishing when Sharing by link is disabled

### PR DESCRIPTION
**Pull request by tcitworld**
Fixes https://github.com/nextcloud/calendar/issues/525 on client side.

Please complete the tests, karma is long time no see.

### CODE REVIEW

**Comment by tcitworld** [comment]
Fixes on server will require more fixes here.

**Comment by georgehrke** [comment]
Will look into the tests asap.

**Comment by georgehrke** [comment]
@tcitworld Is there already a corresponding server side pull-request?

**Comment by georgehrke** [comment]
@tcitworld Can you please double-check my changes :)

**Comment by tcitworld** [comment]
> Fixes on server will require more fixes here.

These includes for example handling public links when the sharing link feature is disabled, resulting in a 410 server error).

**Comment by tcitworld** [comment]
Your changes are valid. :)

**Comment by georgehrke** [comment]
> EDIT : I'll push a server changes wip asap.

Any update? :)

**Pull request merged**
