### PR TITLE
show the whole title if the event is long enough

### PR DESCRIPTION
**Pull request by szaimen**
| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

<details>
<summary>For my own testing</summary>

```
docker run -it \
-e CALENDAR_BRANCH=enh/noid/show-whole-title \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.128 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

### CODE REVIEW

**Comment by szaimen** [comment]
@st3iny do you have also some thoughts on this? :)

**Review by st3iny — COMMENTED** [review]
First of all, I really like this one. I always wondered why there is so much unused space.

I did some testing and it turns out that there is a reason for this. When the title is so long that it is truncated even with your changes, it won't show the three dots.

Sadly, this can't be solved because the css `text-ellipsis` attribute can only handle a single line. There is an unstandardized extension which is supported by some modern browsers (ref https://caniuse.com/?search=line-clamp and https://stackoverflow.com/a/34559614).

Screenshot 2021-12-14 at 15-04-01 Woche 50 aus 2021 - Kalender - calendar-3814-manual

**Comment by szaimen** [comment]
Unfortunately, I don't think that we can use line-clamp here as we would need to specify the exact number of lines beforehand, if I understand the documentation correctly: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp

So I'd rather vote for getting this in and doing the line-clamp as follow-up. What do you think? :)

**Comment by st3iny** [comment]
I see. Let's merge it then. IMO, using the space is more important than showing three dots.

**Review by st3iny — APPROVED** [review]

**Pull request merged**
