### PR TITLE
WIP:allow the user to specify the day the weeks starts

### PR DESCRIPTION
**Pull request by adsworth**
Hi,

this PR allows the user to specify the day the weeks starts irrespective of their language.
As I'm a web development noob all input is welcome.

Saving of the the settings on the server doesn't yet work. I'll have to look into that.

### CODE REVIEW

**Comment by georgehrke** [comment]
Hm :/

We intentionally decided against offering that option. There will be a locale / region setting in the server

**Comment by georgehrke** [comment]
cc @jancborchardt

**Comment by adsworth** [comment]
@georgehrke good that I asked before hand. :)
Well if you decide against it, jut close the PR. Maybe then I could start the implementation in the server and once that is there, take it up here again. :)

**Comment by georgehrke** [comment]
You can find the core issue here: https://github.com/nextcloud/server/issues/1781

**Comment by tcitworld** [comment]
Closing here then.

**Pull request closed without merging**
