### PR TITLE
feat: add conference field

### PR DESCRIPTION
**Pull request by st3iny**
Partially addresses #1758 

## Simple Editor

| RW | RO |
| --- | --- |
| grafik | grafik |

## Sidebar Editor

| RW | RO |
| --- | --- |
| grafik | grafik |

### CODE REVIEW

**Comment by tcitworld** [comment]
Did you test the support of the `CONFERENCE` property with various clients? We might want to keep it in the description as well if it's not good enough.

**Comment by st3iny** [comment]
Good point. I just tested it with Thunderbird and it has no support for the field. I guess we should keep the link in the description for now.

**Comment by st3iny** [comment]
We did some testing on Microsoft (Outlook) and Mac OS (Apple Calendar) and it turns out that both clients don't support the field.

The Apple Calendar on Mac has a shared location and conference field that isn't populated from the CONFERENCE field. Manually setting it by scheduling e.g. a Zoom meeting from the client and then exporting the event shows that the link is written into the description field.

Maybe we should use the location field for the link, given that the CONFERENCE field does not seem to be supported well.

**Comment by tcitworld** [comment]
> Maybe we should use the location field for the link, given that the CONFERENCE field does not seem to be supported well.

https://github.com/nextcloud/calendar/issues/2070 has some discussions about that.

Biggest issue is that we (and other 3rd-party apps) then need to handle when the user wants to enter a physical location.

In any case, even if it's not supported anyway, it doesn't hurt to have the `CONFERENCE` property properly initialized. Support may come on other providers at some point.

**Comment by schiessle** [comment]
> Biggest issue is that we (and other 3rd-party apps) then need to handle when the user wants to enter a physical location.

I see the point, but in 90% of all use cases I like it to have the link in the location field. That's also how I send my manually created invitation at the moment. This is easy to find and most calendars offer a way to directly click it on pop-up, etc. I hate this Teams/Google invitations with lots of text, often multiple links and you have to search for the right one.

A argument for the description might be if we want to send more information, e.g. also the dial-in number if the SIP bridge is enabled.

Maybe a good solution would be to pre-file the URL in both fields, description and location? It doesn't hurt because different people might look at different fields first to find the link and it gives the creator of the event the freedom to overwrite each field if they wish without losing the link?

**Comment by st3iny** [comment]
We discussed this in the team and came up with the following plan: 

1. Write the conference URL into the location field.
2. Implement the clickable link thingy for the location field, too.
3. Render the location field as a clickable link in the appointment notification mail (if it contains a link).

**Comment by ChristophWurst** [comment]
@st3iny todos moved into https://github.com/nextcloud/calendar/issues/5389. Feel free to either change this branch/PR to drop the conference and direct everything towards the new goals or start a new PR.

**Comment by st3iny** [comment]
I'll create a new branch and PR.

**Pull request closed without merging**
