### PR TITLE
set ending time one hour later also when clicking on disabled time input (in order to disable allDay)

### LINKED ISSUE #438: Default ending time should be 1 hour later then start
### Steps
1. Enable "skip simple editor"
2. Create a new event
3. Click in the time field and set a time

### Expected
Ending 1 hour later

### Actual
Ending at start, makes no sense and might cause problems....

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #438

### CODE REVIEW

**Comment by nickvergessen** [comment]
For me it now sets the ending time only, instead of start+end when clicking in the disabled start time and selecting anything.

**Comment by georgehrke** [comment]
this is weird oO

**Comment by georgehrke** [comment]
@nickvergessen Can you please check again? :)

**Comment by nickvergessen** [comment]
Works good, although still some minor flickering of the time (it shows 01:00 until you click anywhere and the time selector is closed)

**Pull request merged**
