### PR TITLE
Fix calendar lists not being orderable any more

### PR DESCRIPTION
**Pull request by GVodyanov**
Fix https://github.com/nextcloud/calendar/issues/6501

So the problem with this bug is that the way that dragging the calendars previously worked is conceptually incompatible with the division of calendars into different sections, mostly because of the hidden calendars. The hidden calendars being part of the order, but being in a different place from all the others, causes the order coming from `vue-draggable` to be wrong. Another issue discussed with Christoph is the drag to reorder feature is pretty hard to discover.

Here are a few things I thought about:
- Instead of having one big orderable section, have 3, one for personal, one for shared, and one for deck. This however still doesn't fix the issue of hidden calendars.
- One potential solution to the hidden calendars is making all calendars unhidden when the users starts dragging, but this would be pretty jarring. 
- Have some sort of button indicating that you are able to reorder the calendars (should probably talk with designers)

In the end to make this happen I thought of adding a button which opens a modal with the three sections: personal, shared, and deck, and WITHOUT the hidden calendars section.

### CODE REVIEW

**Comment by GVodyanov** [comment]
What it could look like:

image

**Comment by GVodyanov** [comment]
@ChristophWurst The issue with ignoring hidden calendars is that even though they are hidden, they still make up the "order" of the calendars. So if you have:

- Calendar ID 1
- Calendar ID 2 (hidden)
- Calendar ID 3
- Calendar ID 4

With the order [1, 2, 3, 4]

The draggable list would show:
- Calendar ID 1
- Calendar ID 3
- Calendar ID 4

Now imagine you move Calendar ID 4 to the second position, resulting in:
- Calendar ID 1
- Calendar ID 4
- Calendar ID 3

The order could either be [1, 2, 4, 3] or [1, 4, 2, 3] seeing as the hidden calendar, even if not displayed in the UI, still is part of the list. This causes draggable to give weird results.

There are a few ways that come to mind to solve this: show the hidden calendars when dragging (jarring because they appear out of nowhere), append hidden calendars to the end (messing up the order when u want to hide a calendar), etc. The modal is also one.

**Comment by ChristophWurst** [comment]
> append hidden calendars to the end (messing up the order when u want to hide a calendar)

This :)

See hidden list as extension of the visible calendars list. In your example, the order will be  [ 1 4 3 2 ]. When you unhide the calendar it will be at the bottom of the visible calendars, which seems acceptable to me.

**Review by SebastianKrupinski — APPROVED** [review]
Tested. Works. 

Arranging calendar list order works, unhiding a calendar adds the calendar to the end of the list.

**Comment by LnLcFlx** [comment]
> When you unhide the calendar it will be at the bottom of the visible calendars, which seems acceptable to me.

To me, unfortunately, it is not.
I, and I assume others too, often hide and un-hide calendars based on what I have to see rn (I have lots of calendars), resulting in an unordered mess which one would have to reorder upon every hide/un-hide.

Would the following "align-at-top" solution work, technically?:
- When I drag a calendar B to a new position, what I usually intend to do is to *place said calendar B below another calendar A (in the visible list)*.
  (At least that's how my brain works, after all the list expands from top to bottom).
- Would it be possible to fetch calendar A above calendar B and just insert the calendar ID of B right after A?
- In the above example: When I move calendar 4 up in the visible list to *1, 4, 3* 
  This would turn into a unique ordering [1, 4, 2, 3] because 1 is the calendar in the visible list above 4 after reordering.
- If I move a calendar to the top of the visible list, this ofc should result in an ordering that starts with that calendar (no matter if previously another hidden calendar took the first spot).

It is not perfect but the most intuitive approach, that solves this issue, I could come up with.

**Comment by ChristophWurst** [comment]
Thanks for the proposal, @LnLcFlx. Could you please put this into a new feature request ticket so the idea doesn't get lost?

**Pull request merged**
