### PR TITLE
add proper color-picker

### LINKED ISSUE #4: Color picker for the agendas
Hi ,

Is it possible to replace the limited color chooser by a color picker ?

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #4 

If the browser supports input type color, it will show the proper color-picker instead of the random color button.
If the browser doesn't support input type color, it will just stick to the random color button

please review @nextcloud/calendar

### CODE REVIEW

**Comment by georgehrke** [comment]
> We could optimise the svg a little bit though :)

Can you elaborate on that? :) 
Feel free to just push to this branch

**Comment by skjnldsv** [comment]
This has been discussed here and there in nextcloud, so i retrieved one thread for you https://github.com/nextcloud/nextcloud.com/pull/205

Should be useful :)

**Comment by skjnldsv** [comment]
And we can do even more with svgo:
```
~http/nextcloud-dev/apps/calendar% svgo img/color_picker.svg 
Done in 91 ms!
2.019 KiB - 57.4% = 0.86 KiB
```

**Comment by georgehrke** [comment]
new svg is fancy

**Pull request merged**
