### PR TITLE
Fix mobile widget showing past events and limiting results too much

### PR DESCRIPTION
**Pull request by miaulalala**
for calendar widget

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Did the clients send an empty string?

**Comment by miaulalala** [comment]
> Did the clients send an empty string?

looks like, at least iOS. I asked Marino to test it, so I've left it as a draft for now.

**Comment by miaulalala** [comment]
Maybe this is a clue:
```php
	 * @param array $sinceIds Array indexed by widget Ids, contains date/id from which we want the new items
```

Could be that the value is just... wrong in general. I have disabled the option and will only show the next 14 days now.

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
