### PR TITLE
Timezone simple event

### PR DESCRIPTION
**Pull request by Peterede**
Added timezone to attendee params in SimpleEvent to store and retrieve the timezone for an attendee.

### CODE REVIEW

**Comment by tcitworld** [comment]
@Peterede Can you adapt the tests too ?

**Comment by georgehrke** [comment]
@Peterede Would you mind helping us to review / test https://github.com/nextcloud/calendar/pull/590 ? :) 

It's also related to this pull-request.

**Comment by Peterede** [comment]
I was able to get the tests to run and it returned OK (53 tests, 325 assertions)

**Comment by georgehrke** [comment]
This has been implemented in calendar-js.
https://github.com/georgehrke/calendar-js/blob/master/src/properties/attendeeProperty.js#L173L190

**Pull request closed without merging**
