### PR TITLE
fix(talk): Only invite guest accounts to open Talk conversations

### PR DESCRIPTION
**Pull request by ChristophWurst**
Inviting guests to a private group chat has the implication that the Talk room has to be opened up for guests. This is unexpected.
This patch adjusts the logic to only invite guest users if the Talk room is already open for guests. Otherwise they are ignored.

Fixes https://github.com/nextcloud/calendar/issues/5687

## How to test

Repro steps from https://github.com/nextcloud/calendar/issues/5687

In addition, test it with an open conversation. Guests will be added.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
I could first check the room status and if guests are allowed I still send these participants. Only for private rooms I ignore them.

**Review by AndyScherzinger — APPROVED** [review]

**Comment by ChristophWurst** [comment]
> I could first check the room status and if guests are allowed I still send these participants. Only for private rooms I ignore them.

Done. Please test/review another time

**Review by nickvergessen — APPROVED** [review]

**Comment by miaulalala** [comment]
Works, the guests are not invited to the room if it isn't open.

**Review by miaulalala — APPROVED** [review]

**Pull request merged**
