### PR TITLE
Bump deps / `@nextcloud/webpack-vue-config` and use npm7

### PR DESCRIPTION
**Pull request by skjnldsv**
ref https://github.com/nextcloud/app-tutorial/pull/319

- Feel free to revert all my github actions changes
- There is ONE linting issue that require a bit more attention
- Builds fine BUT didn't look extensively at the ui (seems good at first sight)

### CODE REVIEW

**Review by st3iny — COMMENTED** [review]
I just tested a bit and the UI seems to work fine. 

I have no idea what the linter is trying to tell us:
```
/var/www/nextcloud/dev_apps/calendar/src/components/AppNavigation/Settings/ImportScreenRow.vue
  71:20  error  Unexpected side effect in "calendars" computed property  vue/no-side-effects-in-computed-properties
```
I don't see a side effect in the mentioned computed property :man_shrugging:

**Comment by skjnldsv** [comment]
> I don't see a side effect in the mentioned computed property

Arrays are passed as references, pushing an item into it will update the orignal store value

**Comment by st3iny** [comment]
> > I don't see a side effect in the mentioned computed property
> 
> Arrays are passed as references, pushing an item into it will update the orignal store value

Sure but the linter complains even if I remove the push or slice the array right after obtaining it from the getter.

**Comment by skjnldsv** [comment]
> Sure but the linter complains even if I remove the push or slice the array right after obtaining it from the getter.

image
Indeed

**Comment by st3iny** [comment]
I resolved all conflicts, rebased and fixed all pending issues. Let's get this merged quickly before more conflicts arise and I have to start over again.

@ChristophWurst The required checks have to be adjusted in the repository settings. I renamed the build jobs for consistency with the js tests jobs.

**Review by ChristophWurst — APPROVED** [review]
:+1: but didn' test

**Review by st3iny — APPROVED** [review]
I did some extensive testing and didn't encounter a broken feature.

**Pull request merged**
