### PR TITLE
Add nigthly creation in travis

### PR DESCRIPTION
**Pull request by Gomez**
I put the credentials into the travis-ci settings.

Will work if merged :smile: 
https://travis-ci.org/nextcloud/calendar/builds/161913182

### CODE REVIEW

**Comment by georgehrke** [comment]
@Gomez Is this ready to merge?

Is this some travis feature or do you use yet another service to trigger the builds?

**Comment by Gomez** [comment]
Cron on the Ftp, which triggers the build and upload from travis.
Ready to merge

**Comment by tcitworld** [comment]
LGTM.

**Comment by georgehrke** [comment]
Thx @Gomez :)

**Comment by Gomez** [comment]
@georgehrke Cron is not setup correctly. Will do it, as soon as it works, i will add the infos to the readme.

**Comment by georgehrke** [comment]
Looks like it worked last night though :)
https://nightly.portknox.net/calendar/

**Comment by Gomez** [comment]
Now even better:
https://github.com/nextcloud/calendar/pull/90

**Pull request merged**
