### PR TITLE
add avatar to sharing dropdown

### LINKED ISSUE #207: Add avatar to sharing list
Currently the search dropdown and the list of shares don't use the displayname and the avatar. Instead it only shows the id (ugly on ldap). Both should be fixed.

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #207

### CODE REVIEW

**Comment by georgehrke** [comment]
calendar - nextcloud chromium today at 11 01 01 pm

**Comment by georgehrke** [comment]
The avatars should be added to the sharing list as well, but I'm generally not too happy about the current design of the "shared-with" list.

calendar - nextcloud chromium today at 11 02 38 pm

cc @jancborchardt @eppfel @nextcloud/designers

**Comment by georgehrke** [comment]
I would prefer some design like this: (just like the files app)
files - nextcloud chromium today at 11 08 24 pm

but we have too little space in the navigation bar :/

**Comment by georgehrke** [comment]
cc @nickvergessen who reported the original avatar issue

**Comment by georgehrke** [comment]
And there is no real visual indication whether the expanded area belongs to `test 2` or `test 3`
calendar - nextcloud chromium today at 11 15 00 pm

**Comment by tcitworld** [comment]
> And there is no real visual indication whether the expanded area belongs to test 2 or test 3

Maybe the whole area could have the calendar color instead of just the dot ?

**Comment by georgehrke** [comment]
calendar - nextcloud chromium today at 12 02 31 am

That's with alpha .2

Hm. It could work, but there is no other place in Nextcloud doing it this way.
I'd prefer to use something we already use in other places of Nextcloud.

**Comment by tcitworld** [comment]
> Hm. It could work, but there is no other place in Nextcloud doing it this way.

Yeah well I can't think of any other part of Nextcloud where the sidebar has to be reduced this small to show the calendar aside, so whatever we choose, I guess it wouldn't be just like the files app. :(

**Comment by georgehrke** [comment]
I created an issue about the "shared-with" list: https://github.com/nextcloud/calendar/issues/377

**Comment by tcitworld** [comment]
Works correctly. Just a small issue on my side : 

selection_030

**Comment by georgehrke** [comment]
@tcitworld What browser / os is that? :)

**Comment by tcitworld** [comment]
Firefox 52 on gnu/linux. Chrome/ium doesn't have this issue.

**Comment by georgehrke** [comment]
calendar - nextcloud firefox today at 5 08 32 pm

Looks fine with Firefox on macOS

**Comment by tcitworld** [comment]
Seems to be a resolution issue. If I use the adaptive view of Firefox to change the resolution (including the one I actually use), the issue is gone.

**Comment by jancborchardt** [comment]
By the way, see how the share dropdown is nice and white in the files sidebar – can you take the same styles from there? :)

**Pull request merged**
