### PR TITLE
Change String#replaceAll with String#replace and the g switch

### LINKED ISSUE #2757: Calendar app white page on Firefox version 63.0.1 (nc20)
Hi Devs,

nextcloud 20.0.4
php 7.3
mariadb latest
calendarApp version 2.1.2
Browser Firefox 63.0.1

Calendar App shows only white page when clicked.

I have upgraded now to nc20 and I unfortunatly saw that calendar now shows a white page in Firefox 63.0.1. (It works on Firefox 84) but due to company restrictions I have to work with 63.0.1.

It would be nice if this could be fixed.

Thank you.

EDIT:
#### Browser log
```
GEThttps://mydomain.com/index.php/apps/calendar/
[HTTP/1.1 200 OK 147ms]
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Strict-Transport-Security: The site specified a header that did not include a 'max-age' directive.[Learn More] calendar
GEThttps://mydomain.com/core/js/dist/main.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/core/js/dist/files_fileinfo.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/core/js/dist/files_client.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/js/core/merged-template-prepend.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/core/dd86-2079-server.css?v=35d886836a77b200ed99db01068506d3-acc84847-9
GEThttps://mydomain.com/core/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/accessibility/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/accessibility/js/accessibilityoca.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/apporder/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/apporder/js/apporder.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/core/dd86-2079-css-variables.css?v=35d886836a77b200ed99db01068506d3-acc84847-9
GEThttps://mydomain.com/apps/encryption/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/encryption/js/encryption.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/files_sharing/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/files_sharing/js/dist/main.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/epubreader/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/epubreader/js/plugin.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/files_pdfviewer/js/files_pdfviewer-public.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/files_videoplayer/js/main.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/notifications/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/notifications/js/notifications-main.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/firstrunwizard/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/firstrunwizard/js/about.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/theming/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/theming/js/theming.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/user_status/js/user-status-menu.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/calendar/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/calendar/js/calendar.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/core/js/dist/unified-search.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/apporder/css/apporder.css?v=cfab4291-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/notifications/0577-2079-styles.css?v=35d886836a77b200ed99db01068506d3-acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/deck/bf70-2079-deck.css?v=35d886836a77b200ed99db01068506d3-acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/notes/23fb-2079-global.css?v=35d886836a77b200ed99db01068506d3-acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/spreed/8869-2079-unified-search.css?v=35d886836a77b200ed99db01068506d3-acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/user_status/3acc-2079-user-status-menu.css?v=35d886836a77b200ed99db01068506d3-acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/calendar/9562-2079-calendar.css?v=35d886836a77b200ed99db01068506d3-acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/icons/icons-vars.css?v=1608632352
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/apps/theming/styles?v=9
[HTTP/1.1 200 OK 0ms]
Unknown property 'scrollbar-color'.  Declaration dropped. dd86-2079-server.css:1:409
Unknown property 'scrollbar-width'.  Declaration dropped. dd86-2079-server.css:1:462
Unknown pseudo-class or pseudo-element '-webkit-scrollbar'.  Ruleset ignored due to bad selector. dd86-2079-server.css:1:2023
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-track-piece'.  Ruleset ignored due to bad selector. dd86-2079-server.css:1:2064
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-thumb'.  Ruleset ignored due to bad selector. dd86-2079-server.css:1:2125
Error in parsing value for 'position'.  Declaration dropped. dd86-2079-server.css:1:2352
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:2563
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:4185
Unrecognised at-rule or error parsing at-rule '@-ms-viewport'. dd86-2079-server.css:1:23285
Unknown property 'appearance'.  Declaration dropped. dd86-2079-server.css:1:32555
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:36115
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:47963
Error in parsing value for 'max-width'.  Declaration dropped. dd86-2079-server.css:1:50083
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:52100
Unknown pseudo-class or pseudo-element '-webkit-progress-value'.  Ruleset ignored due to bad selector. dd86-2079-server.css:1:53569
Unknown pseudo-class or pseudo-element '-webkit-progress-bar'.  Ruleset ignored due to bad selector. dd86-2079-server.css:1:53632
Unknown pseudo-class or pseudo-element '-webkit-progress-value'.  Ruleset ignored due to bad selector. dd86-2079-server.css:1:53814
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. dd86-2079-server.css:1:54288
Unknown pseudo-class or pseudo-element '-webkit-search-cancel-button'.  Ruleset ignored due to bad selector. dd86-2079-server.css:1:66832
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:84583
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:86511
Error in parsing value for 'position'.  Declaration dropped. dd86-2079-server.css:1:96950
Error in parsing value for 'position'.  Declaration dropped. dd86-2079-server.css:1:121660
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:128250
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:128909
Unknown property 'line-break'.  Declaration dropped. dd86-2079-server.css:1:132180
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:136652
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. apporder.css:18:10
Error in parsing value for 'word-wrap'.  Declaration dropped. 0577-2079-styles.css:1:2592
Unknown property 'user-select'.  Declaration dropped. 9562-2079-calendar.css:1:9476
Error in parsing value for 'max-width'.  Declaration dropped. 9562-2079-calendar.css:1:33578
No OC found index.js:46:4
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:541
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
Notifications permissions denied App.vue:302
GEThttps://mydomain.com/index.php/avatar/flonext/32?v=0
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/svg/core/logo/logo?color=fff&v=1
[HTTP/1.1 200 OK 0ms]
XHRGEThttps://mydomain.com/ocs/v2.php/apps/notifications/api/v2/notifications
[HTTP/1.1 200 OK 196ms]
XHRPUThttps://mydomain.com/index.php/apps/user_status/heartbeat
[HTTP/1.1 204 No Content 260ms]
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:48:9
Unknown property 'user-select'.  Declaration dropped. calendar:178:14
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:667:10
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:1044:9
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:1051:9
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:1055:9
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:1307:10
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:175:9
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:182:9
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:186:9
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:438:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:132:11
Unknown property '-moz-border-radius'.  Declaration dropped. calendar:136:22
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:146:11
Unknown property '-moz-border-radius'.  Declaration dropped. calendar:150:22
Unknown property 'zoom'.  Declaration dropped. calendar:9:10
Expected declaration but found '*'.  Skipped to next declaration. calendar:10:5
Unknown property 'user-select'.  Declaration dropped. calendar:49:27
Error in parsing value for 'background-image'.  Declaration dropped. calendar:53:23
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. calendar:55:13
Error in parsing value for 'background-image'.  Declaration dropped. calendar:69:23
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. calendar:71:13
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:137:13
Error in parsing value for 'background-image'.  Declaration dropped. calendar:202:23
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. calendar:204:13
Error in parsing value for 'background'.  Declaration dropped. calendar:261:887
Error in parsing value for 'background'.  Declaration dropped. calendar:271:888
Error in parsing value for 'background'.  Declaration dropped. calendar:283:2529
Error in parsing value for 'background-image'.  Declaration dropped. calendar:307:23
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. calendar:309:13
Error in parsing value for 'background-image'.  Declaration dropped. calendar:319:23
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. calendar:321:13
Unknown property 'user-select'.  Declaration dropped. calendar:395:27
Unknown property 'user-select'.  Declaration dropped. calendar:582:27
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. calendar:585:13
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:15:10
Unknown property 'line-break'.  Declaration dropped. calendar:1:208
Error in parsing value for 'left'.  Declaration dropped. calendar:1:490
Error in parsing value for 'left'.  Declaration dropped. calendar:1:811
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1117
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1434
Unknown property 'line-break'.  Declaration dropped. calendar:1:208
Error in parsing value for 'word-break'.  Declaration dropped. calendar:1:71
Unknown property 'backdrop-filter'.  Declaration dropped. calendar:1:689
XHRGEThttps://mydomain.com/ocs/v2.php/search/providers?from=%2Fapps%2Fcalendar%2F
[HTTP/1.1 200 OK 335ms]
Error in parsing value for 'position'.  Declaration dropped. calendar:1:167
Unknown property 'user-select'.  Declaration dropped. calendar:1:385
Unknown pseudo-class or pseudo-element '-ms-clear'.  Ruleset ignored due to bad selector. calendar:1:34858
Unknown property 'user-select'.  Declaration dropped. calendar:1:35648
Unknown property 'user-select'.  Declaration dropped. calendar:1:38971
Error in parsing value for 'left'.  Declaration dropped. calendar:1:490
Error in parsing value for 'left'.  Declaration dropped. calendar:1:811
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1117
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1434
Unknown property 'line-break'.  Declaration dropped. calendar:1:208
Error in parsing value for 'max-width'.  Declaration dropped. calendar:1:1924
Unknown property 'user-select'.  Declaration dropped. calendar:1:4129
Unknown property 'line-break'.  Declaration dropped. calendar:1:208
Error in parsing value for 'left'.  Declaration dropped. calendar:1:490
Error in parsing value for 'left'.  Declaration dropped. calendar:1:811
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1117
XHRGEThttps://mydomain.com/index.php/apps/apporder/getOrder
[HTTP/1.1 200 OK 229ms]
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1434
Unknown property 'line-break'.  Declaration dropped. calendar:1:208
Unknown pseudo-class or pseudo-element '-ms-clear'.  Ruleset ignored due to bad selector. calendar:1:34858
Unknown property 'user-select'.  Declaration dropped. calendar:1:35648
Unknown property 'user-select'.  Declaration dropped. calendar:1:38971
Unknown property 'line-break'.  Declaration dropped. calendar:1:208
Error in parsing value for 'left'.  Declaration dropped. calendar:1:490
Error in parsing value for 'left'.  Declaration dropped. calendar:1:811
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1117
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1434
Unknown property 'line-break'.  Declaration dropped. calendar:1:208
Error in parsing value for 'left'.  Declaration dropped. calendar:1:490
Error in parsing value for 'left'.  Declaration dropped. calendar:1:811
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1117
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1434
Unknown property 'user-select'.  Declaration dropped. calendar:13:23
Unknown property 'user-select'.  Declaration dropped. calendar:86:23
Unknown property 'speak'.  Declaration dropped. calendar:90:9
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. calendar:99:27
Error in parsing value for 'outline'.  Declaration dropped. calendar:151:22
Unknown property 'user-select'.  Declaration dropped. calendar:176:25
Error in parsing value for 'position'.  Declaration dropped. calendar:397:15
Error in parsing value for 'position'.  Declaration dropped. calendar:414:13
Error in parsing value for 'position'.  Declaration dropped. calendar:41:17
ReferenceError: ResizeObserver is not defined[Learn More] autosize.js:25:6
Unknown property 'line-break'.  Declaration dropped. calendar:1:208
Error in parsing value for 'left'.  Declaration dropped. calendar:1:490
Error in parsing value for 'left'.  Declaration dropped. calendar:1:811
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1117
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1434
Unknown property 'rx'.  Declaration dropped. calendar:1:295
Unknown property 'ry'.  Declaration dropped. calendar:1:319
Unknown property 'x'.  Declaration dropped. calendar:1:501
Unknown property 'y'.  Declaration dropped. calendar:1:570
Unknown property 'y'.  Declaration dropped. calendar:1:638
Unknown pseudo-class or pseudo-element '-webkit-search-decoration'.  Ruleset ignored due to bad selector. calendar:1:986
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
session heartbeat polling started session-heartbeat.js:97:1
Files_PDFViewer initialized for public page 
Object { isPublicPage: null, canDownload: true, isSecureViewerAvailable: false }
public.js:30:1
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
Strict-Transport-Security: The site specified a header that did not include a 'max-age' directive.[Learn More] notifications
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
Strict-Transport-Security: The site specified a header that did not include a 'max-age' directive.[Learn More] heartbeat
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
Strict-Transport-Security: The site specified a header that did not include a 'max-age' directive.[Learn More] getOrder
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, … }
ConsoleLogger.js:42:10
Strict-Transport-Security: The site specified a header that did not include a 'max-age' directive.[Learn More] providers
XHRGEThttps://mydomain.com/index.php/apps/encryption/ajax/getStatus
[HTTP/1.1 200 OK 145ms]
XHRGEThttps://mydomain.com/ocs/v2.php/apps/user_status/api/v1/user_status
[HTTP/1.1 200 OK 214ms]
GEThttps://mydomain.com/apps/calendar/img/favicon-touch.png
GEThttps://mydomain.com/apps/calendar/img/favicon.ico
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
Strict-Transport-Security: The site specified a header that did not include a 'max-age' directive.[Learn More] getStatus
Strict-Transport-Security: The site specified a header that did not include a 'max-age' directive.[Learn More] user_status
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2 
```

### PR DESCRIPTION
**Pull request by tcitworld**
Fixes compatibility up to at least Firefox 60 (well, at least loading the initial screen).

Closes #2757 (and probably a lot of similar issues).

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by PatriceVigier** [comment]
Thank you but...sorry I cannot find the file where the code to change is located.
Where is it ?
Thank you

**Comment by raimund-schluessler** [comment]
> I do not have src/fullcalendar/localization/localeProvider.js

As the file path tells, this is the source code. You will have to compile the Calendar from the source code as explained in the docs https://github.com/nextcloud/calendar#build-the-app. Or better wait for the next (maintenance) release.

**Comment by PatriceVigier** [comment]
Thank you

Nightly built link is broken

**Comment by tcitworld** [comment]
You may try with this package I've just built, but we don't offer *any* kind of support for it.
[calendar.tar.gz](https://github.com/nextcloud/calendar/files/5831595/calendar.tar.gz)

**Comment by PatriceVigier** [comment]
**Thank you** tcitworld, it works like a charm

**Comment by syntron** [comment]
> You may try with this package I've just built, but we don't offer _any_ kind of support for it.
> [calendar.tar.gz](https://github.com/nextcloud/calendar/files/5831595/calendar.tar.gz)

I can confirm that the updated tar file works in falkon - it is just a replacement for 2.1.3 wit the latest updates ...

**Pull request merged**
