### PR TITLE
Dashboard: Filter events before now

### PR DESCRIPTION
**Pull request by georgehrke**
| Before | After |
|:---------:|:------:|
|C284BB19-9D51-4853-8F67-906CCA280D6F|07845959-A616-41CA-B740-09C3F28FE304|

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:+1: Makes sense

**Review by juliushaertl — APPROVED** [review]

**Review by jancborchardt — APPROVED** [review]
Yeah, let’s do it like this for now – simplest fix. :) cc @rullzer

**Comment by jancborchardt** [comment]
@georgehrke only one thing actually, sorry – the "All day today" event should actually show, no? So only stuff that has started before today should be hidden.

**Comment by georgehrke** [comment]
Well, but the "long day from the past event" also takes place today. It's just that it started yesterday already.

**Comment by jancborchardt** [comment]
Yeah, but still there’s a difference if an event e.g. a conference starts _today_ and you put it in so you remember, vs it is running already and you kinda know about it since yesterday or a few days ago already.

**Comment by georgehrke** [comment]
https://github.com/nextcloud/calendar/pull/2579

**Pull request merged**
