### PR TITLE
Changed highlighting of the current day to be more visible

### PR DESCRIPTION
**Pull request by bbBowser**
Changed color of current day, to be more visible on screens with bad contrast (from #ffc to #ffa)

### CODE REVIEW

**Comment by georgehrke** [comment]
Hey :)

Thx for your contribution! :)
When submitting design pull requests please always provide before and after screenshots.

Please also explain why you think this change is necessary.

Thx :)

**Comment by bbBowser** [comment]
Sorry for those short explanations ;)
I had problems to find the current day on several laptop or office screens, when the viewing angle was not perfect.
I think the current highlight has not enough contrast to fit those "not perfectly calibrated screens".
Since made it just a little darker, the overall appearance is not changed very much.

before:
grafik

after:
grafik

Thx for your patience and good work,
bbBowser

**Comment by tcitworld** [comment]
Related https://github.com/nextcloud/calendar/issues/119

**Comment by georgehrke** [comment]
pls review @nextcloud/designers :)

**Comment by enoch85** [comment]
OK with me as well :+1:

**Comment by georgehrke** [comment]
btw, I don't mean to hijack this thread, but most other calendar applications color the days of the weekend slightly grey.
Did we decide against that intentionally? If yes, why?

**Comment by enoch85** [comment]
@georgehrke Gray is better imho actually.

**Pull request merged**
