### PR TITLE
nc12 emailtemplate follow up

### PR DESCRIPTION
**Pull request by georgehrke**

### CODE REVIEW

**Comment by georgehrke** [comment]
follow up for https://github.com/nextcloud/calendar/pull/476

**Comment by georgehrke** [comment]
screenshot

**Comment by enoch85** [comment]
:+1:

**Comment by jancborchardt** [comment]
The body text completely duplicates the title though … this is not really necessary, and we should simplify it.

**Comment by georgehrke** [comment]
@jancborchardt Can you suggest a different body text? :) 

I'd be happy to change it

**Comment by jancborchardt** [comment]
I would just show the header and the button, nothing more. :)

**Pull request merged**
