### PR TITLE
chore(deps): Move tools into a Composer bin

### PR DESCRIPTION
**Pull request by ChristophWurst**

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Bin plugin doesn't install for the cs-fixer jobs somehow

**Review by miaulalala — APPROVED** [review]

**Review by st3iny — COMMENTED** [review]
Needs a post-install-cmd to automatically install binned dependencies. (Potentially a post-update-cmd too? We have that in Mail.)

```json
{
    "scripts": {
        "post-install-cmd": ["@composer bin all install --ansi"]
    }
}
```

Ref https://github.com/bamarni/composer-bin-plugin#auto-installation
Ref https://github.com/nextcloud/mail/blob/e940ade81aeafec22c9337d1b4ab6a20bdd6d12e/composer.json#L64

**Comment by ChristophWurst** [comment]
I thought the `"forward-command": true` option did that now

**Comment by st3iny** [comment]
> I thought the `"forward-command": true` option did that now: https://github.com/bamarni/composer-bin-plugin#forward-command-forward-command

You are right. I didn't catch that.

**Comment by ChristophWurst** [comment]
I'll try the old approach nevertheless just to see if that is what makes the lint fail right now

**Comment by st3iny** [comment]
Btw, I get the same error locally on a clean installe (git clean -xfd vendor vendor-bin).

```sh
10:51:42 [/srv/http/dev_apps/calendar] git:(chore/deps/move-tools-to-composer-bin)
richard@xps $ composer i
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port) :-(
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 1 install, 0 updates, 0 removals
  - Installing bamarni/composer-bin-plugin (1.8.2): Extracting archive
Generating optimized autoload files

10:51:45 [/srv/http/dev_apps/calendar] git:(chore/deps/move-tools-to-composer-bin)
richard@xps $ composer run cs:check
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port) :-(
> php-cs-fixer fix --dry-run --diff
sh: 1: php-cs-fixer: not found
Script php-cs-fixer fix --dry-run --diff handling the cs:check event returned with error code 127
```

**Comment by ChristophWurst** [comment]
> I thought the `"forward-command": true` option did that now: https://github.com/bamarni/composer-bin-plugin#forward-command-forward-command

The plugin is still at v1.8 :see_no_evil:

**Comment by st3iny** [comment]
Running `composer install` a second time works even without your fixup.

I think the problem is that the plugin is not imported while it is being installed. It is installed on the second run and then it will be executed. The command has to be run twice in a clean/fresh setup.

**Comment by ChristophWurst** [comment]
CI is happy with the exception of packaging. We use composer v1 there. Bump in https://github.com/nextcloud/calendar/pull/5024.

**Comment by ChristophWurst** [comment]
CI still says no

**Comment by ChristophWurst** [comment]
CI is right. There is no bin plugin with `--no-dev` :thinking:

**Comment by ChristophWurst** [comment]
CI is happy

**Pull request merged**
