### PR TITLE
Move resource list and search to a separate tab 

### LINKED ISSUE #3270: Separate attendee and resource tabs
**Describe the solution you'd like**
Separate the room/resource search and list from the attendee tab into its own tab. This paves the way for further improvements to the resource/room search.

**Additional context**
First item of https://github.com/nextcloud/calendar/issues/3184#issuecomment-866201361.

### PR DESCRIPTION
**Pull request by st3iny**
Fixes #3270 

The tab is currently named `Resources` and has a map marker as its icon. I also changed the status for pending resources to `Checking availability.` from `Invitation sent.`. Feedback and suggestions are highly appreciated.

Screenshot 2021-07-02 at 11-28-02 July 2021 - Calendar - Nextcloud

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> Move Reminders & Repeating from tabs to details

https://github.com/nextcloud/calendar/issues/3184#issuecomment-866201361

I think that will be necessary to make the tab names readable again

**Comment by st3iny** [comment]
> > Move Reminders & Repeating from tabs to details
> 
> [#3184 (comment)](https://github.com/nextcloud/calendar/issues/3184#issuecomment-866201361)
> 
> I think that will be necessary to make the tab names readable again

Agreed. I suggest doing that in a another PR though.

New issue to track this change: https://github.com/nextcloud/calendar/issues/3291

**Review by ChristophWurst — APPROVED** [review]
Tested and works :shipit:

**Comment by ChristophWurst** [comment]
@st3iny please rebase, squash and sign off :)

**Comment by st3iny** [comment]
> @st3iny please rebase, squash and sign off :)

Done

**Pull request merged**
