### PR TITLE
Fix copying text to the clipboard

### LINKED ISSUE #4526: Copying text to the clipboard is broken
### Steps to reproduce
1. Use calendar app with latest master
2. Try to copy e.g. the calendar link

### Expected behavior
Clipboard is filled

### Actual behaviour
No text in clipboard

The reason is a change in the nextcloud/vue lib (namely the focus-trap of the popover) that interferes with the way how `vue-clipboard2` copies text. The solution is to use `navigator.clipboard.writeText()` instead, see https://github.com/nextcloud/tasks/pull/2115.

Also ref https://github.com/nextcloud/nextcloud-vue/issues/3275

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Fixes #4526 

Fix copying text to the clipboard
Remove using on vue-clipboard2

See the reference https://github.com/nextcloud/tasks/pull/2115

### CODE REVIEW

**Comment by JuliaKirschenheuter** [comment]
Copying text to the clipboard should be tested with ```https``` connection

**Comment by tcitworld** [comment]
It [should](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) work on localhost as well.

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
Are there no changes to package-lock.json if you drop a dependency?

**Review by ChristophWurst — APPROVED** [review]

**Comment by st3iny** [comment]
> Are there no changes to package-lock.json if you drop a dependency?

Done

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
