### PR TITLE
Fix clipboard copy

### PR DESCRIPTION
**Pull request by EinfachAlex**
Good evening,
since I got the same error as in #4694, I tried to fix it myself. 
Now it works for me again

Before:
brave_iAlhjYwI9K
brave_XqKjoxP19p

After:
brave_Z7HsCF75Kr
brave_l0dRX5t7sJ

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
This must have been missing from https://github.com/nextcloud/calendar/pull/4577 :+1:

**Comment by ChristophWurst** [comment]
I'm setting DCO to pass for the two lines changes as they do not yet qualify for authorship certificate. When you submit your next PR please make sure to *sign-off* the commits: https://wiki.linuxfoundation.org/dco :)

**Comment by iT-Boyer** [comment]
The issue is repeated in Nextcloud 25 | calendar 4.2.4

**Pull request merged**
