### PR TITLE
fix layout for slotduration of one hour

### PR DESCRIPTION
**Pull request by szaimen**
| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

<details>
<summary>For my own testing</summary>

```
docker run -it \
-e CALENDAR_BRANCH=enh/noid/slot-duration \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.128 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

### CODE REVIEW

**Comment by miaulalala** [comment]
I tested on Chrome. Did npm ci and npm run build but I don't see your proposed changes. Am I missing a step?

**Comment by szaimen** [comment]
> I tested on Chrome. Did npm ci and npm run build but I don't see your proposed changes. Am I missing a step?

Yes, you need to set the time interval to 1 hour in the settings. (Is at 30min by default)

**Comment by miaulalala** [comment]
Yes I changed to 1 hour layout, but the change isn't there. I'm suspecting a JS cache issue but icognito also doesn't show the changes.

**Comment by szaimen** [comment]
> Yes I changed to 1 hour layout, but the change isn't there. I'm suspecting a JS cache issue but icognito also doesn't show the changes

strange 🤔 let me test again...

**Comment by szaimen** [comment]
let me test again...

works for me without any problem

<details>
<summary>Tested with</summary>

```
docker run -it \
-e CALENDAR_BRANCH=enh/noid/slot-duration \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.128 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

**Pull request merged**
