### PR TITLE
l10n: Triple dot ellipsis

### PR DESCRIPTION
**Pull request by rakekniven**
Reported at Transifex.

Signed-off-by: rakekniven <mark.ziegler@rakekniven.de>

### CODE REVIEW

**Comment by georgehrke** [comment]
@rakekniven I fixed some more :)

**Comment by tcitworld** [comment]
Also make sure we have a [non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space) before the ellipsis so that it doesn't go on another line in some cases (we shouldn't have those, but still).

**Comment by tcitworld** [comment]
`eslint` is not happy about the non-breaking spaces.

**Comment by georgehrke** [comment]
I opened an issue in our eslint-config: https://github.com/nextcloud/eslint-config-nextcloud/issues/9

**Pull request merged**
