### PR TITLE
revert: Augment the category menu by system tags and already used categories

### PR DESCRIPTION
**Pull request by miaulalala**
Ref b3af4c3

### CODE REVIEW

**Comment by ChristophWurst** [comment]
This should also go into main (or even main first, then backport) so we don't have a blocked main branch for the next minor release.

Critical paths to test and offer a migration will be events that now have a custom category set. They should at least render and be editable. Ideally the category should be removable.

**Comment by miaulalala** [comment]
Codecov upload is failing

**Comment by miaulalala** [comment]
Tested the categories - I can manually add a separate category 'testing' and remove it again.

**Comment by ChristophWurst** [comment]
Cc @rotdrop 

This reverts https://github.com/nextcloud/calendar/pull/5161 to remedy https://github.com/nextcloud/calendar/issues/5476

**Review by ChristophWurst — COMMENTED** [review]
Change looks good

**Comment by rotdrop** [comment]
> Cc @rotdrop
> 
> This reverts #5161 to remedy #5476

Sad story, but I understand that this is a problem. I'll have a look at the SQL things. Perhaps it would be possible to have some lazy autocompletion setup on-demand instead of just loading everything from the DB at page load.

**Comment by ChristophWurst** [comment]
The change can be brought back once the performance issues are gone.

**Comment by tcitworld** [comment]
> Sad story, but I understand that this is a problem. I'll have a look at the SQL things. Perhaps it would be possible to have some lazy autocompletion setup on-demand instead of just loading everything from the DB at page load.

Yes, that is a good lead. Add with that some cache and it might be acceptable.

**Review by kesselb — APPROVED** [review]

**Pull request merged**
