### PR TITLE
fix(rtl): navigation buttons

### LINKED ISSUE #6402: Navigation buttons should be flipped
### Steps to reproduce

Image

### Expected behavior

Good design

### Actual behaviour

Bad design 

### Calendar app version

_No response_

### CalDAV-clients used

_No response_

### Browser

_No response_

### Client operating system

_No response_

### Server operating system

_No response_

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

_No response_

### Updated from an older installed version or fresh install

None

### List of activated apps

_No response_

### Nextcloud configuration

_No response_

### Web server error log

_No response_

### Log file

_No response_

### Browser log

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by hamza221**
fix #6402
| b | a |
|--------|--------|
| image | https://github.com/user-attachments/assets/e334b714-4049-4367-8f87-aec766020365 |

### CODE REVIEW

**Comment by DorraJaouad** [comment]
From the test
|Before (main) | after |
--|--
image | image


The direction of change is now correct but the arrow directions should remain as in main.
( e.g: the left side button was leading to previous months and now it leads to recent months)

**Comment by hamza221** [comment]
@DorraJaouad are you on latest master (server) ?

**Comment by DorraJaouad** [comment]
> @DorraJaouad are you on latest master (server) ?

No, master is now updated 🙈 

The directions should be the opposite (e.g: left side button leads to next month)

https://github.com/user-attachments/assets/9dbd31a8-9d68-4a6c-9c25-108c6c18a297

**Review by DorraJaouad — APPROVED** [review]
Tested

**Review by st3iny — APPROVED** [review]
LGTM! Was tested by a native speaker.

**Pull request merged**
