### PR TITLE
better tabindex for event editors

### LINKED ISSUE #25: improve tab index in editor

### PR DESCRIPTION
**Pull request by georgehrke**
please review @ccoenen @eppfel 

fixes #25

### CODE REVIEW

**Comment by tcitworld** [comment]
Tab goes from title to the « All day event » checkbox without going through the dates before.

**Comment by ccoenen** [comment]
This is exactly the point of this pull request, see https://github.com/nextcloud/calendar/issues/25 and https://github.com/nextcloud/calendar/issues/72

I won't have time to properly review this myself for at least another week, I'm sorry.

**Comment by tcitworld** [comment]
> This is exactly the point of this pull request, see #25 and #72

That's why I reviewed it…

**Comment by georgehrke** [comment]
> Tab goes from title input to the « All day checkbox » without going through the date selectors first.

Yes, that's intended. :)

**Comment by georgehrke** [comment]
@ccoenen Do you have time to review this pr this week? :)

**Comment by tcitworld** [comment]
> > Tab goes from title input to the « All day checkbox » without going through the date selectors first.

> Yes, that's intended. :)

Not sure why. Can't seem to find where this was decided. It's certainly more logical to go through the « All day » checkbox before the time selectors, but why before the date selectors ?

**Comment by georgehrke** [comment]
This pr was mostly about getting feedback by @ccoenen @eppfel 
so we can test this concept.
Sorry for not communicating that properly.

When creating an event in month view, all-day is disabled by default.
If you want to create an event with time you have to:
Enter event name <Tab> select calendar <Tab>  <Tab>  <Tab> deselect all-day  <Shift-Tab>  <Shift-Tab>  <Shift-Tab> select time  <Tab>  select end date  <Tab>  select end time <enter>

That's very complex. 

With this PR, its:
Enter event name <Tab> select calendar <Tab> deselect all-day <Tab> <Tab> select time  <Tab>  select end date  <Tab> select end time <enter>

**Comment by eppfel** [comment]
I mean, in the details sidebar it would be possible to jump start-date, end-date, all-day-event, and than if activated start-time, end-time. But in the popup it not really makes sense. So I think this is the best solution. The problem is just the missing :focus on checkboxes, but that's a different issue.

**Comment by georgehrke** [comment]
> Not sure why. Can't seem to find where this was decided. It's certainly more logical to go through the « All day » checkbox before the time selectors, but why before the date selectors ?

So you are suggesting the following?
```
Start-Date <Tab> End-Date <Tab> Checkbox <Tab> Start-time <Tab> end-time
```

I'm really not sure about that, because start-date and start-time (same goes for end) are very closely bound together from an information point of view. Having to enter the end date in between would probably confuse me.

**Comment by georgehrke** [comment]
@tcitworld Are you fine with this approach or is this a no-go for you?

**Comment by tcitworld** [comment]
In fact I didn't check the popup when I was saying this. For the popup it's actually good, but for the sidebar I still find it quite bothering. It can be done in another PR though.

**Pull request merged**
