### PR TITLE
Fix overlapping toggle also in Firefox

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/calendar/pull/5475#issuecomment-1730188885
Close https://github.com/nextcloud/groupware/issues/2

### CODE REVIEW

**Review by raimund-schluessler — APPROVED** [review]
Day and Week view are fine now 👍

**Comment by szaimen** [comment]
CI failure unrelated afaics

**Review by st3iny — APPROVED** [review]
Tested and works.

**Pull request merged**
