### PR TITLE
Add confirmation to appointment config modal

### LINKED ISSUE #3606: Add a confirmation to the appointment config modal

### PR DESCRIPTION
**Pull request by st3iny**
Fix #3606

Screenshot 2021-11-09 at 13-12-50 November 2021 - Calendar - Nextcloud

### CODE REVIEW

**Comment by st3iny** [comment]
I highly recommend hiding whitespace changes when reviewing my code.

**Review by ChristophWurst — APPROVED** [review]
Code looks good viewed as https://github.com/nextcloud/calendar/pull/3624/files?w=1

**Review by GretaD — APPROVED** [review]
tested and it works. The copy link button is now shown on the pop up. Should it always show when i update?

**Comment by st3iny** [comment]
> The copy link button is now shown on the pop up. Should it always show when i update?

Good question. Let's talk about this in the next design review.

**Pull request merged**
