### PR TITLE
Default time to 10am to 11am when changing from allDay to timed

### LINKED ISSUE #532: Feature Request: Tweak Default Start Time
### Steps to reproduce
1. Create an event (it defaults to "All Day")
2. Uncheck the All day Event checkbox
3. The start time for the event is set at 12 AM

It's a minor thing, but I don't have too many events that start at midnight. :) Google Calendar currently defaults to 10 AM which is a nice feature in my opinion. As it is now, if a user unchecks the "All day Event" checkbox and forgets to update the start time, they can get reminders in the middle of the night.

Again, it's a minor issue, but I thought I would bring it up. Keep up the great work.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/46968720-feature-request-tweak-default-start-time?utm_campaign=plugin&utm_content=tracker%2F45525646&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F45525646&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #532

### CODE REVIEW

**Comment by tcitworld** [comment]
Shouldn't we consider current time when the day is today?

**Comment by georgehrke** [comment]
I'm not sure if the behaviour should be different for one particular day.

But my idea for https://github.com/nextcloud/calendar/issues/1021 was that when you click "New event" it will automatically open the new event on today and round up to the next hour.
Does that make sense?

**Comment by tcitworld** [comment]
> I'm not sure if the behaviour should be different for one particular day.

My use case was when you have an all day event on today's date and uncheck the all day checkbox, it's odd to default to an already passed time. It's not that important though, so I'm fine with ignoring it for now.

> But my idea for #1021 was that when you click "New event" it will automatically open the new event on today and round up to the next hour.
Does that make sense?

Yes.

**Comment by tcitworld** [comment]
See #1567

**Pull request merged**
