### PR TITLE
Fix misplaced empty content

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Fixes https://github.com/nextcloud/calendar/issues/5933

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
image | Screenshot from 2024-04-19 15-49-08

### CODE REVIEW

**Comment by tcitworld** [comment]
The text also seems to lack a little horizontal padding ?

**Review by miaulalala — DISMISSED** [review]
Please add some padding-left and padding-right too.

**Review by st3iny — APPROVED** [review]
Still works.

**Review by hamza221 — APPROVED** [review]

**Review by miaulalala — APPROVED** [review]

**Pull request merged**
