### PR TITLE
fix scrollability of calendar-list

### PR DESCRIPTION
**Pull request by georgehrke**
possible fix for https://github.com/nextcloud/calendar/issues/68

please review @raghunayyar @tcitworld

### CODE REVIEW

**Comment by tcitworld** [comment]
calendar-scroll

- [ ] Increase the width of the sidebar so that there's no scrollbar on x

**Comment by georgehrke** [comment]
What browser/OS is that?

**Comment by tcitworld** [comment]
Firefox 48/Debian

**Comment by georgehrke** [comment]
Okay, so we should decrease the width of the new calendar field.

The width of the app navigation is defined in the nextcloud server styles. I would rather not override that.

**Comment by tcitworld** [comment]
> The width of the app navigation is defined in the nextcloud server styles. I would rather not override that.

Indeed, but that leave even less space for long calendar names. :(

**Comment by georgehrke** [comment]
we could also say `overflow-x: hidden`

**Comment by tcitworld** [comment]
I think I had tested and it makes list item not centered and maybe even hid the Create button a little. Still acceptable though.

**Comment by georgehrke** [comment]
the initial spinner moved a bit to the left. that needs to be fixed

**Comment by tcitworld** [comment]
calendar-scroll-2

Not perfect, but that the only issue and I can go with it.

**Comment by georgehrke** [comment]
Yes, it's still a huge improvement over the current situation :)

**Comment by raimund-schluessler** [comment]
For the Tasks app I used something like
```
display: inline-flex;
flex-wrap: wrap;
width: 100%;
```
for the colorpicker and
```
width: calc(100% - XX px);
```
for the input field. This leads to a look like this:

**Pull request merged**
