### PR TITLE
Language: Removed redundant "successfully"

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by jancborchardt** [comment]
Good call – but it would also be good to add context, like what was imported:

> Imported calendar **Personal**

or

> Imported event **Open Source Design Summit**

**Comment by comradekingu** [comment]
@jancborchardt Add that if you want. I would approve, albeit maybe not truly ideal, the potential for error would be on the side of caution by specifying.

**Comment by jancborchardt** [comment]
@georgehrke or someone of @nextcloud/calendar can you add the calendar/event name in this feedback message?

**Comment by georgehrke** [comment]
I can take care, but this is not as trivial as it might sound. 
Something for 1.7.0

**Comment by georgehrke** [comment]
Needs a proper implementation in the vue app + cdav-library

**Pull request closed without merging**
