### PR TITLE
Add illustration for (romantic) date as per Jan's suggestion

### PR DESCRIPTION
**Pull request by georgehrke**
https://github.com/nextcloud/calendar/issues/968#issuecomment-531820371

### CODE REVIEW

**Comment by tcitworld** [comment]
I feel it's a little risky to have `date` in English but other than that it's fine.

**Comment by georgehrke** [comment]
I totally agree, but I wasn't sure what other word to use.

**Comment by tcitworld** [comment]
Thinking about it, I've realized there's no real good French translation of (romantic) *date*, as *rendez-vous* can be a business meeting or appointment and *rencard* is kinda slang. It matters pretty much only on the context of your sentence, and I feel it might be the same for other languages.

Is it worth it to have this if people might have the wrong illustration? Maybe we should restrict to proper and common nouns that have only one meaning?

(To be fair I've never entered any of my romantic dates into my calendar)

**Comment by georgehrke** [comment]
I'm also fine with not adding it. :)

Let's close this pull-request for now.

**Pull request closed without merging**
