### PR TITLE
Add support to open event by id

### PR DESCRIPTION
**Pull request by leonklingele-work**
This allows to directly open the 'Edit meeting' modal / sidebar by
accessing an URL like the following:

    /apps/calendar/#!?edit=Nextcloud-EVENTIDHERE.ics

### CODE REVIEW

**Comment by georgehrke** [comment]
Please use the `HashService`.

Why did you go for `#!?` ?

**Comment by leonklingele-work** [comment]
> Why did you go for #!? ?

`$location.search()` otherwise doesn't return anything :/

**Comment by georgehrke** [comment]
See https://github.com/nextcloud/calendar/blob/00c67ab949ee6df6705a6fea57d24594e8229511/js/app/controllers/calendarlistcontroller.js#L335 for usage of `HashService`

**Comment by georgehrke** [comment]
Generally using `clientEvents` won't work, because not all events are cached in fullcalendar. The calendar only loads events that are actually displayed to the user. 

If the event in question is in the previous month, it won't be in the fullcalendar cache.

**Comment by georgehrke** [comment]
Closing

This approach is not working and also won't work in the future, because fullCalendar's `clientEvents` is never gonna contain all events a user owns.

**Pull request closed without merging**
