### PR TITLE
Updated public.scss with overflow property.

### PR DESCRIPTION
**Pull request by SakshiT25**
Fixes https://github.com/nextcloud/calendar/issues/4715

### CODE REVIEW

**Comment by SakshiT25** [comment]
Here's my pull request for the issue. Kindly review.
Thanks.

**Comment by SakshiT25** [comment]
Kindly review the request. 
TIA.

**Review by st3iny — CHANGES_REQUESTED** [review]
I appreciate your contribution but this does not fix the issue.

**Comment by st3iny** [comment]
Hey @SakshiT25, why did you close the PR? Is something wrong?

The new commit looks good to me.

**Comment by st3iny** [comment]
Nevermind, I just saw the new PR :see_no_evil:

**Pull request closed without merging**
