### PR TITLE
Fix events being editable by invitees

### LINKED ISSUE #947: Anyone can become event's organiser and then do anything with event, even cancel it
### Steps to reproduce
1. User A creates an event, invites mailing list BC@email.domain, this list contains users B and C
2. Calendar C is shared to user B read-only, and both calendars B and C are connected into user B Thunderbird
3. User B receives an invitation email with Thunderbird, there is no buttons "Access" or "Decline" but there is "Details" button instead. 
4. User B presses "Details" button and opens event's properties
5. The property "Calendar" contains calendar C. User B changes it to calendar B and suddenly becomes an organiser of event and got it in his calendar.
6. If user B deletes this event from his calendar, it will be deleted from calendars A and C as well.

### Expected behaviour
Tell us what should happen
User B must not become the event's organiser and must not have such access.
### Actual behaviour
Tell us what happens instead
User B becomes the owner of event and now can delete it.
### Server configuration

**Operating system**:
FreeBSD 11.1-RELEASE-p9
**Web server:**
apache 2.4
**Database:**
10.2.14-MariaDB
**PHP version:**
PHP 7.2.4
**Server version:** (see your admin page)
14.0.3
**Calendar version:** (see the apps page)
1.6.3
**Updated from an older installed version or fresh install:**
updated
**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/66403217-anyone-can-become-event-s-organiser-and-then-do-anything-with-event-even-cancel-it?utm_campaign=plugin&utm_content=tracker%2F45525646&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F45525646&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by st3iny**
Fixes #947 

Events should be read only if invitees view them. Only the alarms can be edited.

### CODE REVIEW

**Comment by tcitworld** [comment]
I didn't follow that closely… does this mean as a sharee I can no longer edit events inside a calendar that is shared with me? 

Shouldn't it only affect the invites section (because of https://github.com/nextcloud/server/issues/26668 ?)

**Comment by ChristophWurst** [comment]
> I didn't follow that closely… does this mean as a sharee I can no longer edit events inside a calendar that is shared with me?
> 
> Shouldn't it only affect the invites section (because of [https://github.com/nextcloud/server/issues/26668 ](https://github.com/nextcloud/server/issues/26668%C2%A0)?)

Not quite. This PR doesn't address events on shared calendars but invites to events in your own calendar, where the invitees receive a copy of the even in their personal calendar. That event is currently editable, though the changes go nowhere. With @st3iny's patch the event copy is read-only and only reminders can be edited.

**Review by ChristophWurst — APPROVED** [review]

**Comment by tcitworld** [comment]
> This PR doesn't address events on shared calendars but invites to events in your own calendar

I see that that's the intention, but I fail to see how it wouldn't affect an event (of which I'm not the organizer) I have in my calendar which someone shared to me.

**Comment by ChristophWurst** [comment]
>  I fail to see how it wouldn't affect an event (of which I'm not the organizer) I have in my calendar which someone shared to me

@st3iny you tested that as well, right?

**Comment by st3iny** [comment]
Yes, this introduces a new edge case. 

1. Person 1 creates a calendar and shares it with Person 2 (with edit rights).
2. Person 1 creates an event in said calendar.
3. Person 2 invites Person 1 to the event.
4. The event will be read only for Person 1 even though he created it. 

IMO, this bug is out of scope for this PR because we're currently not tracking the owner of an event.

**Comment by ChristophWurst** [comment]
we forgot about this one. @st3iny please rebase and then we merge & backport :)

**Review by miaulalala — APPROVED** [review]
LGTM

**Comment by ChristophWurst** [comment]
@miaulalala could you rebase and test on top of latest master?

**Comment by miaulalala** [comment]
Testing looks good, just some superflous stuff I merged might still be in there. @st3iny, if you could look through it again?

**Comment by st3iny** [comment]
The changes to `InviteeList*` might need to be ported to `ResourceList*`. I'll give it a final test run.

**Comment by st3iny** [comment]
Ready to merge

**Comment by st3iny** [comment]
I actually managed to fix the edge case I mentioned way back then. 

Turns out I was wrong about tracking the owner. While we can't track the owner of an event we can track the owner of its calendar. I added an extra condition to always allow edits to the owner of the calendar.

**Pull request merged**
