### PR TITLE
Clean all superposed white backgrounds

### PR DESCRIPTION
**Pull request by skjnldsv**
See https://github.com/nextcloud/server/pull/1657/

### CODE REVIEW

**Comment by georgehrke** [comment]
Can you please rebase?

I fixed the style lint error on master

**Comment by georgehrke** [comment]
I just rebased

**Comment by georgehrke** [comment]
👍

**Comment by georgehrke** [comment]
the server pr should be merged first though

**Comment by georgehrke** [comment]
cc @raghunayyar

**Comment by skjnldsv** [comment]
Yes. But we need to settle nextcloud/server# first :)

**Comment by raghunayyar** [comment]
Big thumbs up :+1:

**Comment by skjnldsv** [comment]
We'll se after the scss pr.

**Pull request closed without merging**
