### PR TITLE
fix: edit calendar modal debounced save

### PR DESCRIPTION
**Pull request by st3iny**
Fix https://github.com/nextcloud/calendar/issues/4890

I completely removed the debounced saving logic as it showed too many bad side effects. It has already been removed for the color some time ago.

The modal will be saved on close if there are any changes to color and/or name.

I also added a toast in case saving fails.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> The modal will be saved on close if there are any changes to color and/or name.

We could add a dedicated *Save* button

**Comment by nimishavijay** [comment]
> Add a dedicated save button to save changes.

I woud go with this option, possibly it seems less confusing as I remember there was a previous discussion about the delete button being in the primary button region. So how about something like this:

image

Changes from current state:
- [ ] Dedicated save button like you mentioned
- [ ] Copy private link goes with the other share links
- [ ] rest of the options are on the left as tertiary buttons. Alternatively they could be inside a 3dot menu next to the save button on the left 

What do you think? ccing @jancborchardt as it is a change from his original idea :)

**Comment by jancborchardt** [comment]
Nice! Detail: "Private link" should be "Internal link" and have an explanatory subline like in Files?

**Comment by tcitworld** [comment]
> Copy private link goes with the other share links

In that case, maybe with a UI difference (Icon outlined or something like that)? Private links *should* be less important (less often used at least) than public links.

**Comment by st3iny** [comment]
Closing in favor of https://github.com/nextcloud/calendar/pull/5205.

**Pull request closed without merging**
