### PR TITLE
feat: implement dedicated calendar modal save button

### LINKED ISSUE #4890: UI for editing calendar shares' name loses focus on every character typed
### Steps to reproduce

1. Edit a share's name
2. Modify "rapidly" (I'm not a pro typer) the name of the calendar

### Expected behavior

The new name should reflect what has been typed

### Actual behaviour

The focus is lost for half a second for every character that is being typed. 
Hence, the field "loses" some input.
It only works if you type very slowly.

For example, here I typed (or tried to) "This is the new name":

[Github.webm](https://user-images.githubusercontent.com/5951377/211544229-425223b6-70bc-4d74-a68a-001c66204623.webm)

### Calendar app version

4.2.1

### CalDAV-clients used

_No response_

### Browser

Firefox 108.0.2

### Client operating system

Debian Linux and Windows

### Server operating system

Ubuntu Server 20.04

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 7.4

### Nextcloud version

25.0.2

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

_No response_

### Nextcloud configuration

_No response_

### Web server error log

_No response_

### Log file

_No response_

### Browser log

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by st3iny**
Fixes #4890 

Ref https://github.com/nextcloud/calendar/pull/5187#issuecomment-1533238302 for a mockup

I created a new (feature) PR because some changes can't be backported. It contains new translations.

grafik

### CODE REVIEW

**Comment by st3iny** [comment]
I don't think a backport is necessary as the only relevant branch is stable4.2 which will be replaces by a new minor soon (on all supported Nextcloud versions).

**Comment by tcitworld** [comment]
Thanks! I wouldn't list Thunderbird as it's been featuring calendar discovery for a few versions (so no need anymore to manually copy calendars URIs), but the sentence still works without the last two words.

**Comment by st3iny** [comment]
> Thanks! I wouldn't list Thunderbird as it's been featuring calendar discovery for a few versions (so no need anymore to manually copy calendars URIs), but the sentence still works without the last two words.

Done

**Review by miaulalala — APPROVED** [review]
Works, tested editing the name, sharing with a user, unsharing, changing editing rights

**Pull request merged**
