### PR TITLE
add second step for calendar deletion as a temporary solution

### LINKED ISSUE #341: Add confirm() when deleting a calendar/event
Yes, blocking modals suck, but right now there is no undo action. We are at a dead end with #148 and #149 and it will take at least another 2 or 3 months before https://github.com/nextcloud/server/issues/1662 is implemented and released as stable.

A blocking modals still sucks less than accidentally loosing an entire calendar.

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #341 

please review @tcitworld @raimund-schluessler

### CODE REVIEW

**Comment by georgehrke** [comment]
any update @tcitworld @raimund-schluessler? :)

**Comment by raimund-schluessler** [comment]
Sorry, I haven't had time to review this. Will do so at the weekend.

**Comment by raimund-schluessler** [comment]
Works in principle, only the styling of the confirmation dialog needs some finetuning:
confirmation

- [ ] The cancel and trashbin icons are not centered.
- [ ] The trashbin icon becomes red on hover.
- [ ] The cursor changes when hovering the trashbin icon.
- [ ] The trashbin icon has an opacity.

If you are fine with me pushing to this branch I could fix it.

**Comment by georgehrke** [comment]
What browser are you using? :)

**Comment by georgehrke** [comment]
> If you are fine with me pushing to this branch I could fix it.

Yes, that would be great :)

**Comment by raimund-schluessler** [comment]
This is Firefox 51.0.1 on Windows 10.

ff265806d2e7f7bfd530fe552ebe11a581557ebc fixes it for me

**Comment by georgehrke** [comment]
You are on windows 10!? Do you mind testing https://github.com/nextcloud/calendar/pull/329? ^^

Thx for the fix. Will test asap :)

**Comment by raimund-schluessler** [comment]
> You are on windows 10!? Do you mind testing #329? ^^

I can do that. It is just a bit complicated, since the build is somehow broken for me. The minification of the vendor files always fails. 😕

**Comment by georgehrke** [comment]
I can confirm your patch! 
Thx :)

**Comment by georgehrke** [comment]
will push a css style fix

**Pull request merged**
