### PR TITLE
Duplicate calendar event

### PR DESCRIPTION
**Pull request by szaimen**
Close https://github.com/nextcloud/calendar/issues/113

Based on https://github.com/nextcloud/calendar/pull/2621
Supersedes https://github.com/nextcloud/calendar/pull/2621
Close https://github.com/nextcloud/calendar/pull/2621

Signed-off-by: szaimen <szaimen@e.mail.de>

<details>
<summary>For my own testing</summary>

```
docker run -it \
-e CALENDAR_BRANCH=enh/113/duplicate-event \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.130 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

### CODE REVIEW

**Review by st3iny — APPROVED** [review]
Tested and works. I improved the documentation a bit and renamed the actual cloning method from `map...` to `copyFrom...Into...` because it confused me.

**Comment by szaimen** [comment]
🎉🎉🎉🎉🎉

**Comment by xeruf** [comment]
Using calendar 3.5.0, I cannot find this option?
image

**Comment by st3iny** [comment]
@xeruf It may not work for recurring events if no recurrence exception can be created. Try it with regular events.

**Comment by xeruf** [comment]
Have it now, thank you :)
One weird behavior: When I duplicate an event off a recurring event, I cannot configure recurrence as it says that the event is already a recurrence exception.
But when I save the duplicated event and select it again, it is suddenly an independent event and can have recurrence configure.

**Pull request merged**
