### PR TITLE
use proper constants

### PR DESCRIPTION
**Pull request by georgehrke**
- [x] tests need to be fixed

### CODE REVIEW

**Comment by georgehrke** [comment]
- [ ] rename `defaultView` to `initialView`

**Comment by georgehrke** [comment]
please review @nextcloud/calendar

**Comment by tcitworld** [comment]
I have issues with the `skipPopover` setting. Once activated, it doesn't deactivate when I uncheck the checkbox, either directly or with a page refresh.

**Comment by tcitworld** [comment]
Needs rebase too. :)

**Comment by georgehrke** [comment]
on it already :)

**Comment by georgehrke** [comment]
> I have issues with the `skipPopover` setting. Once activated, it doesn't deactivate when I uncheck the checkbox, either directly or with a page refresh.

That was too obvious  🙈 🙈 🙈 

`settings.skipPopover` and `settings.showWeekNr` are strings

**Comment by georgehrke** [comment]
@tcitworld please check again

**Comment by georgehrke** [comment]
rebased

**Comment by georgehrke** [comment]
please review again @tcitworld :)

**Pull request merged**
