### PR TITLE
refresh events every 5 minutes

### PR DESCRIPTION
**Pull request by georgehrke**
partial fix for https://github.com/nextcloud/calendar/issues/31

### CODE REVIEW

**Comment by tcitworld** [comment]
Why not PROPFIND too every 5 minutes ?

**Comment by georgehrke** [comment]
Note to myself - there is one more issue:
- click existing event to edit it
- try to drag it -> won't work because its locked
- wait for refresh to kick in
- dragging now suddenly works -> that's not how it's supposed to be

Possible solution:
- take fcEvent that's supposed to be edited
- remove it from calendar
- use `renderEvent` with `stick=true` to render as individual event

**Comment by georgehrke** [comment]
@tcitworld PROPFIND takes twice the requests.

Also when it comes to refreshing calendars, it'd like to keep the original object from the initial request and not replace it every 30 seconds ^^

**Comment by tcitworld** [comment]
Rebased.

**Comment by georgehrke** [comment]
Needs a proper implementation in the vue app + cdav-library

**Pull request closed without merging**
