### PR TITLE
IE11 support

### PR DESCRIPTION
**Pull request by georgehrke**

### CODE REVIEW

**Comment by tcitworld** [comment]
Is it a demand of the NC guys enterprise subscriptions or are you a masochist ?

**Comment by georgehrke** [comment]
Yes, its customer related.

**Comment by georgehrke** [comment]
@tcitworld Can you please review? :) 

You probably don't have an IE for testing around, but testing that everything still works in Firefox/Chromium would be awesome!

**Comment by tcitworld** [comment]
Will try to boot a Windows device later today. :)

**Comment by georgehrke** [comment]
That would be awesome, thx! :)

**Comment by georgehrke** [comment]
@tcitworld any update yet? :)

**Comment by raimund-schluessler** [comment]
With IE v11.576:

In the JS console:
```
stack"TypeError: Das Objekt unterstützt die Eigenschaft oder Methode "registerProtocolHandler" nicht ...
```

Call to `http://192.168.56.2/nextcloud/remote.php/dav/calendars/admin/calendar-with-long-name/`:
Request:
```
<c:calendar-query xmlns:NS1="" NS1:xmlns:a="http://apple.com/ns/ical/" xmlns:NS2="" NS2:xmlns:cs="http://calendarserver.org/ns/" xmlns:NS3="" NS3:xmlns:d="DAV:" xmlns:NS4="" NS4:xmlns:c="urn:ietf:params:xml:ns:caldav" xmlns:NS5="" NS5:xmlns:o="http://owncloud.org/ns" xmlns:NS6="" NS6:xmlns:n="http://nextcloud.com/ns"><d:prop><d:getetag /><c:calendar-data /></d:prop><c:filter><c:comp-filter name="VCALENDAR"><c:comp-filter name="VEVENT"><c:time-range start="20170129T230000Z" end="20170312T230000Z" /></c:comp-filter></c:comp-filter></c:filter></c:calendar-query>
```

Answer:
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\Xml\LibXMLException</s:exception>
  <s:message>xmlns:NS1: Empty XML namespace is not allowed
 on line 1, column 28</s:message>
</d:error>
```

**Comment by georgehrke** [comment]
you rebuild the sources with gulp, right?

**Comment by georgehrke** [comment]
> stack"TypeError: Das Objekt unterstützt die Eigenschaft oder Methode "registerProtocolHandler" nicht ...

That's fine. That's inside a try catch block

**Comment by raimund-schluessler** [comment]
> you rebuild the sources with gulp, right?

I am sorry. I used `make`, but since the build process is broken for me I forgot to manually build the JS file. After doing so the calendars are loading fine. I can edit the calendar (change color or name, etc.) and editing and creating events also works.

There are some small style issues, e.g. the icon for edit button is not visible, but in general it works well.
ie

**Comment by raimund-schluessler** [comment]
Btw. `make` works fine. The reason for it to fail was insufficient memory of my Virtual Machine.

**Comment by georgehrke** [comment]
thx for testing :)

**Comment by jacestk** [comment]
Hi all,
[New issue on IE11 for 1.6.0 with NC13](https://github.com/nextcloud/calendar/issues/732)

**Pull request merged**
