### PR TITLE
Show import button on first run

### LINKED ISSUE #19: show import calendar button below new calendar button if no writable calendars exist

### PR DESCRIPTION
**Pull request by georgehrke**
fix #19 

please review @eppfel @tcitworld @jancborchardt 

to test this delete the 'currentView' row from oc_preferences.
To test it again delete both the 'currentView' and 'firstRun' row.

### CODE REVIEW

**Comment by tcitworld** [comment]
Looks good. I'll test asap.

**Comment by tcitworld** [comment]
Strange that the coverage decreased.

**Comment by georgehrke** [comment]
Hm, yes.
That's probably because the settingsController is not tested at all yet.

**Comment by georgehrke** [comment]
@jancborchardt @eppfel @tcitworld I would like to get this in today, would be great if you could review this.

**Comment by tcitworld** [comment]
👍

**Pull request merged**
