### PR TITLE
use NC12 IEMailTemplate for fancier emails

### LINKED ISSUE #427: Better designed emails when sharing calendar
Today we use standard templates that contains mostly text. It works, but isn't that pretty. What I suggest is to improve the design so that it looks more professional. I've seen some great work by @Espina2 the past weeks, and I'd really like to see some suggestions regarding an improvment of the mails that are sent to users.

As an external user of Nextcloud (someone that uses Nextcloud sends a link to someone that doesn't) the first impression is the mail they get with either a calendar invitavion or a shared link. To attract more users to use Nextcloud and make a switch from Google or some other provider I belive it's crucial that our soulution looks better.

Google Calendar invitation:
markering_002

The server emails are merged by @MorrisJobke and now it's only the calendar emails left.. It currently looks like this in Thunderbird:
calendar

It would be great if that also was merged before 12 is release so that we can close this issue.

Thank you! :)

Copy pasted from here: https://github.com/nextcloud/server/issues/2071

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #427 

email

I didn't find a way to make the calendar name bold yet :/

### CODE REVIEW

**Comment by georgehrke** [comment]
I'm thinking about adding »« like in the files app

inbox ehrke email 5 238 messages mail today at 5 17 46 pm

**Comment by tcitworld** [comment]
> I'm thinking about adding »« like in the files app

Makes it quite strange IMHO, as a French, we're not used to see this since we use french quotes « citation » just like regular quotes. Maybe we can leave this up to the translators to choose.

**Comment by enoch85** [comment]
Cc @espina2

**Comment by enoch85** [comment]
What I miss when invited to an event:
Accept | Decline | Maybe (if maybe is an option?)

Also; information about who invited you, which calendar it is (name), and place of the event.

The Google pics describes it pretty good in this issue: https://github.com/nextcloud/calendar/issues/427 (Even though the red is not so nice ;) )

**Comment by georgehrke** [comment]
@enoch85 Server issue ;)

**Comment by enoch85** [comment]
@georgehrke >  Server issue ;)

So what you mean is that the DAV endpoint doesn't support it? :open_mouth:

**Comment by georgehrke** [comment]
> So what you mean is that the DAV endpoint doesn't support it?

The dav end point the part of the server ;)

**Comment by enoch85** [comment]
I may be mistaken, but it should be possible to extract the info that you can type in, because you can add info about:
- Attendee
- Time 
- Place
- Who invited you is just about showing the name of the sender which could be extacted from the Display name (right?)

Or do you mean that `Accept | Decline | Maybe (if maybe is an option?)` is not possible?

**Comment by georgehrke** [comment]
Yes, that's possible. But not the calendar app but the server sends out the invitation emails ;)

**Comment by enoch85** [comment]
Aah, I should go to bed now :)

**Comment by enoch85** [comment]
Design wise :+1:

**Comment by Espina2** [comment]
@georgehrke @enoch85 if you want to highlight something just use a plain bold. It should be enough.

**Comment by georgehrke** [comment]
Hm, sorry for this stupid question, but what do you mean with plain bold? 

`<b> </b>` doesn't work

**Comment by enoch85** [comment]
@Espina2 

> Hm, sorry for this stupid question, but what do you mean with plain bold?

Ping

**Comment by Espina2** [comment]
```<strong>``` is the html default markup for bold

**Comment by georgehrke** [comment]
`<strong>` will be escaped just like `<b>`

**Comment by georgehrke** [comment]
check the first screenshot. It shows `<b>Geburtstage von Freunden</b>`.

If I use `<strong>`, it will just be `<strong>Geburtstage von Freunden</strong>`.

**Comment by georgehrke** [comment]
I don't seem to find a way to add bold text looking thru the [EMailTemplate.php](https://github.com/nextcloud/server/blob/master/lib/private/Mail/EMailTemplate.php)

Let's go with »« for now. Translators will have the chance to replace that with "" or any other local standard.

**Comment by enoch85** [comment]
> Let's go with »« for now. Translators will have the chance to replace that with "" or any other local standard.

Let's do this! :rocket:

**Comment by georgehrke** [comment]
No No No 🙈

**Comment by enoch85** [comment]
Oops :D

**Comment by georgehrke** [comment]
@enoch85 Please don't merge stuff with "2 - developing" ;)

**Comment by enoch85** [comment]
Aiai sir :+1:

**Comment by georgehrke** [comment]
I will just open a follow up PR

**Pull request merged**
