### PR TITLE
Fixed #1893

### LINKED ISSUE #1893: Sharing a calendar with groups doesn't get saved (v2.0.1)
### Steps to reproduce
1. Share a calendar with a group -> it looks as if it's accepted
2. Reload: the share was not saved
3. side note: sharing with a single user still works correctly
Problem appears since calendar upgrade this morning via web interface

### Expected behaviour
Sharing with a group should be possible as before

### Actual behaviour
Shared with group is not saved

### Calendar app
**Calendar app version:** 2.0.1

### Client configuration
**Browser:** (e.g. Firefox 48)
Tested on 
* Firefox 72.0.1 on Ubuntu 19.10
* Firefox 68.4.2 ESR on Windows 10 1803
* Safari on iPad (latest versions)
* Microsoft Edge (not the new Chromium engine) on Windows 10 1803

### Server configuration

**Operating system**: (e.g. Debian 8)
Debian

**Web server:** (e.g. Apache, Nginx,...)
Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MySQL

**PHP version:** 
7.3

**Nextcloud Version:**
17.0.2

**Updated from an older installed version or fresh install:**
Updated since 17.0

**List of activated apps:**

Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - apporder: 0.9.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.8
  - dav: 1.13.0
  - deck: 0.8.0
  - encryption: 2.5.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_antivirus: 2.2.1
  - files_mindmap: 0.0.15
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - groupfolders: 5.0.5
  - groupquota: 0.1.2
  - guests: 1.3.1
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 1.0.0
  - nextcloud_announcements: 1.6.0
  - notes: 3.1.1
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - ocr: 5.0.4
  - ojsxc: 4.0.0-rc.1
  - password_policy: 1.7.0
  - polls: 1.0.0
  - provisioning_api: 1.7.0
  - quota_warning: 1.6.0
  - ransomware_protection: 1.5.1
  - recommendations: 0.5.0
  - richdocuments: 3.5.1
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - sharerenamer: 2.7.3
  - spreed: 7.0.2
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_admin: 2.0.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_nextcloud_notification: 2.2.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0

### PR DESCRIPTION
**Pull request by der-Daniel**
## Description

The URI to the DAV resource has not been url-decoded.

Fixes #1893

### CODE REVIEW

**Comment by der-Daniel** [comment]
I tried to get this sign off thing into my last commit and force pushed it.

Is there another way of doing this? AFAIK I can only edit mt commit message by force pushing it once it is in the remote origin.

**Comment by SuperSandro2000** [comment]
You did the correct thing but the mail is not matching according to DCO. Take a look here https://github.com/nextcloud/calendar/pull/1985/checks?check_run_id=438913803 .

To get there click on the checks tab at the top, expand DCO and click on the entry.
Would wish that the "Details" links would go there.

**Comment by der-Daniel** [comment]
Fixed it. This sign off was new to me. :+1:

**Comment by georgehrke** [comment]
I'm sorry, but this is not a real fix from my pov, rather a hot fix.

The problem is that the contents of `<d:path>` inside the principal-property-search is wrongly encoded. Just open the developer console and inspect the network request when searching for users / groups.

**Comment by georgehrke** [comment]
Reopening as of https://github.com/nextcloud/server/issues/17610#issuecomment-588992903

**Comment by georgehrke** [comment]
B6F7E732-DD50-45C0-AC1F-1B90C227C8D1

This breaks not showing groups already shared with.

**Comment by georgehrke** [comment]
If you change [line 150](https://github.com/nextcloud/calendar/pull/1985/files#diff-c73136095f873c19579a48d9130fbdffR150) to the following, it works as expected:

```
				if (hiddenPrincipals.includes(decodeURI(result.principalScheme))) {
```

**Comment by der-Daniel** [comment]
This is another bug/feature, I guess, because AFAIK they never showed up in the search if they are a sharee.

**Comment by georgehrke** [comment]
@der-Daniel Are you gonna fix line 150 or should I? :)

**Comment by der-Daniel** [comment]
Just pushed it. Thanks for this finding!

**Comment by georgehrke** [comment]
My current plan is to have Calendar 2.0.2 by the end of next week.

**Pull request merged**
