### PR TITLE
feat(editors): redesign editors

### PR DESCRIPTION
**Pull request by st3iny**
Fix https://github.com/nextcloud/calendar/issues/3543

### Simple Editor

| Read-only | Edit mode | View Mode |
| --- | --- | --- |
| simple-ro | simple-rw-edit | simple-rw-view |

### Sidebar Editor

| Header | Attachments | Read-only |
| --- | --- | --- |
| sidebar-rw | attachments | sidebar-ro |

### Invitations

I moved the invitation response button below the date and time fields. They looked a bit awkward at the bottom.

| Simple | Sidebar |
| --- | --- |
| simple-invitation | sidebar-invitation |

## TODO

- [x] Sidebar redesign
- [x] Attachments redesign
- [x] Fix conflicts

### CODE REVIEW

**Review by GretaD — APPROVED** [review]
it looks like in the screenshots, and no errors were shown. :partying_face:

**Comment by GretaD** [comment]
ah, i have this warning while building:

`WARNING in ./node_modules/moment/min/moment-with-locales.js 2159:16-50
Module not found: Error: Can't resolve './locale' in '/var/www/nextcloud/server/apps/calendar/node_modules/moment/min'
 @ ./node_modules/@nextcloud/moment/dist/index.mjs 1:0-50 2:0-65 6:0-8 9:58-72 9:73-81 15:0-17:2
 @ ./src/filters/dateRangeFormat.js 22:0-39 36:13-19 39:16-22 40:14-20 43:13-19 47:13-19
 @ ./src/services/windowTitleService.js 22:0-60 42:18-33
 @ ./src/main.js 41:0-66 67:0-18
`

**Comment by st3iny** [comment]
> ah, i have this warning while building:
> 
> `WARNING in ./node_modules/moment/min/moment-with-locales.js 2159:16-50 Module not found: Error: Can't resolve './locale' in '/var/www/nextcloud/server/apps/calendar/node_modules/moment/min' @ ./node_modules/@nextcloud/moment/dist/index.mjs 1:0-50 2:0-65 6:0-8 9:58-72 9:73-81 15:0-17:2 @ ./src/filters/dateRangeFormat.js 22:0-39 36:13-19 39:16-22 40:14-20 43:13-19 47:13-19 @ ./src/services/windowTitleService.js 22:0-60 42:18-33 @ ./src/main.js 41:0-66 67:0-18 `

Yeah, that is likely related to a recent bump of nextcloud/moment https://github.com/nextcloud/calendar/pull/5699. I'll have a look next week but it should not be related to this PR.

I'll also fix js unit tests ASAP.

**Comment by st3iny** [comment]
Blocked until the nextcloud/vue 8 migration was merged.

**Review by nimishavijay — CHANGES_REQUESTED** [review]
This is super super cool! :D really great :) Some minor comments:
- [x] The title of the event could be more eye catching, so it could be bold and even in bigger font size 
- [ ] All the icons on the left could be center aligned. Currently the icon of the details are slightly more to the left, the icon of the calendar on top is a bit to the right, and the icons in the top and bottom section in the sidebar are slightly misaligned. All these should ideally be center aligned :) (suggestion: add some left margin for the details elements in the card and the top section of the sidebar) 
- [ ] There should also be an icon for the date time, it could be the [event MDI icon](https://fonts.google.com/icons?selected=Material%20Icons%20Round%3Aevent%3A)

Nice-to-haves that are not in the original mockups:
- [ ] if there is no recurrence, the "No recurrence" wording can be changed to "Does not repeat" to keep it simple
- [ ] Use a [edit icon](https://fonts.google.com/icons?selected=Material%20Icons%20Round%3Aedit%3A) for the edit button 
- [ ] Use a [done icon](https://fonts.google.com/icons?selected=Material%20Icons%20Round%3Adone%3A) for the save button

Regarding the accept/reject/tentative buttons:
- [ ] You are right, placing it directly as the last row looks off. I am not sure about placing such bold buttons in the middle of the card either. How about placing it as the second-last row and making the edit button a tertiary button?
- [ ] Hide accept/decline/reject buttons in edit mode

Artboard-2

Or alternatively no full width buttons, but all right justified
Artboard-1

What do you think? Also pinging the rest of @nextcloud/designers for your thoughts on the accept buttons :)

**Comment by szaimen** [comment]
> Or alternatively no full width buttons, but all right justified
> Artboard-1

I like this one. It is not so much `in your face` compared to the other one 😅

**Comment by skjnldsv** [comment]
Oh, I just realized we don't have the illustrations on the sidebar anymore :(
I loved those!

**Pull request merged**
