### PR TITLE
Follow up to design changes in month view

### LINKED ISSUE #3865: Follow up to design changes in month view
@dartcafe please delete the above mentioned code again since @jancborchardt agreed to make it globablly for all views.

---

```
		.fc-event {
			box-shadow: 0px 0px 0px 1px var(--color-primary-light) !important;
		}
```
and
```
		&.fc-col-header-cell {
			background-color: var(--color-primary-light);
		}
```
is probably still missing from the global styling though...

_Originally posted by @szaimen in https://github.com/nextcloud/calendar/pull/3817#discussion_r778673360_

### PR DESCRIPTION
**Pull request by dartcafe**
fix #3865
before | after
-|-
grafik | grafik

### CODE REVIEW

**Review by jancborchardt — APPROVED** [review]
Nice, thank you! :)

**Comment by dartcafe** [comment]
I am satified, that I now understood the request. ;-)

**Review by szaimen — CHANGES_REQUESTED** [review]
will do some changes here

**Review by szaimen — APPROVED** [review]
this should be it now

**Pull request merged**
