### PR TITLE
Enable PHP 7.4 stable on Travis

### PR DESCRIPTION
**Pull request by tcitworld**

### CODE REVIEW

**Comment by tcitworld** [comment]
https://travis-ci.community/t/some-extensions-are-missing-in-php-7-4-0-zip-gmp-sodium/6320/22

**Comment by tcitworld** [comment]
Can we move to `xenial`?

**Comment by raimund-schluessler** [comment]
Another option would be to move away from travis completely and use Github actions: https://github.com/nextcloud/app-tutorial/tree/master/.github/workflows

**Comment by georgehrke** [comment]
I think we should go for @raimund-schluessler's suggestion and move to GitHub actions.

@tcitworld Any objections?

**Comment by tcitworld** [comment]
> @tcitworld Any objections?

Nope, I never played much with Github Actions, that's why I didn't go ahead.

**Pull request closed without merging**
