### PR TITLE
Bundle and minify vendor files

### LINKED ISSUE #323: ship minified versions of everything in js/vendor/

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #323

### CODE REVIEW

**Comment by skjnldsv** [comment]
Could you provide a before/after load test?
This is interesting! :)

**Comment by georgehrke** [comment]
`siege -t60s -c20 -d10 --header="Authorization:Basic YWRtaW46YWRtaW4=" 'http://nextcloud.dev/index.php/apps/calendar/'`

with bundling and minifying:
```
Lifting the server siege...
Transactions:                   1340 hits
Availability:                 100.00 %
Elapsed time:                  59.19 secs
Data transferred:              53.54 MB
Response time:                  0.87 secs
Transaction rate:              22.64 trans/sec
Throughput:                     0.90 MB/sec
Concurrency:                   19.73
Successful transactions:        1340
Failed transactions:               0
Longest transaction:            9.48
Shortest transaction:           0.00
```

without bundling and minifying:
```
Lifting the server siege...
Transactions:                   1517 hits
Availability:                 100.00 %
Elapsed time:                  59.80 secs
Data transferred:              91.28 MB
Response time:                  0.77 secs
Transaction rate:              25.37 trans/sec
Throughput:                     1.53 MB/sec
Concurrency:                   19.59
Successful transactions:        1517
Failed transactions:               0
Longest transaction:           10.73
Shortest transaction:           0.01
```

**Comment by georgehrke** [comment]
This makes more sense:

`siege -r6 -c20 -d10 --header="Authorization:Basic YWRtaW46YWRtaW4=" 'http://nextcloud.dev/index.php/apps/calendar/'`

with:
```
Transactions:                   8280 hits
Availability:                 100.00 %
Elapsed time:                 371.50 secs
Data transferred:             325.53 MB
Response time:                  0.80 secs
Transaction rate:              22.29 trans/sec
Throughput:                     0.88 MB/sec
Concurrency:                   17.91
Successful transactions:        8280
Failed transactions:               0
Longest transaction:           10.24
Shortest transaction:           0.00
```

without:
```
Transactions:                   9480 hits
Availability:                 100.00 %
Elapsed time:                 373.44 secs
Data transferred:             552.86 MB
Response time:                  0.70 secs
Transaction rate:              25.39 trans/sec
Throughput:                     1.48 MB/sec
Concurrency:                   17.88
Successful transactions:        9480
Failed transactions:               0
Longest transaction:           10.36
Shortest transaction:           0.00
```

**Comment by georgehrke** [comment]
and this is localhost,
`Data transferred: 325.53 MB` and `Data transferred: 552.86 MB` will make a big difference in real world use cases.

**Comment by georgehrke** [comment]
@tcitworld Bundling and Minifying the `vendor.js` and `vendor.min.js` takes a couple of seconds. That's why I decided to bundle them in a `vendor.js` instead of `app.js`. Otherwise everytime you change code and regenerate the `app.js`, you have to wait these extra couple of seconds.

**Comment by skjnldsv** [comment]
Wow! Very nice work!

**Comment by georgehrke** [comment]
@skjnldsv Is that an approve? :P

**Comment by skjnldsv** [comment]
@georgehrke on your work! Yeah!
Haven't tested though :)

**Comment by georgehrke** [comment]
please review @tcitworld :)

**Comment by tcitworld** [comment]
Couldn't we get rid of the sourcemaps in production environment ?

**Comment by georgehrke** [comment]
> Couldn't we get rid of the sourcemaps in production environment ?

AFAIK the source maps are only loaded when you open the developer console.
Am I wrong?

**Comment by tcitworld** [comment]
Nope, that's right.

**Comment by georgehrke** [comment]
Ok, so I'd like to keep it, because:
- it makes the package thats downloaded only once slightly larger
- it doesn't affect ordinary users
- it will make debugging in production easier 

Do you agree? :)

**Comment by skjnldsv** [comment]
I agree with @georgehrke too :)

**Comment by tcitworld** [comment]
Of course.

**Comment by georgehrke** [comment]
cool, thanks for reviewing :)

**Pull request merged**
