### PR TITLE
hide sidepanel on print view

### PR DESCRIPTION
**Pull request by tcitworld**
Hides the sidebar on print view.

We also could consider bundling https://github.com/fullcalendar/fullcalendar/blob/master/src/common/print.css

### CODE REVIEW

**Comment by tcitworld** [comment]
We should also change the title of the window to match the current view so that it's printed on the headers : https://github.com/nextcloud/calendar/issues/280

**Comment by georgehrke** [comment]
The PR is working as described in the PR. But you won't be able to see which color belongs to which calendar. 
This is definitely better then the current solution, but we need a proper print styles in the long run.
I will create an issue.

**Comment by georgehrke** [comment]
there already is: https://github.com/nextcloud/calendar/issues/136

**Comment by alexanderdd** [comment]
@georgehrke hmm, left panel is not hidden for me in print view in NC 18.0.6 calendar 2.0.3 firefox 79.0
also the calendars in the sidebar have no colors next to them so you dont know which calendar belongs to which events

**Pull request merged**
