### PR TITLE
fix month view

### PR DESCRIPTION
**Pull request by szaimen**
<details><summary>Sry for the private links but I've used my private data on this to show it on real data. Don't know if thats the best way to do it...  If someone wants to show it on fake data, please go ahead and just create the videos and substitute the ones that I've created.</summary>

## Before 
https://cloud.nextcloud.com/f/4058580

## After
https://cloud.nextcloud.com/f/4058585

</details>

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
@tcitworld do you want to have a look, too?

**Comment by tcitworld** [comment]
Can you PM me public links on the cloud?

**Comment by szaimen** [comment]
> Can you PM me public links on the cloud?

You should be able to view them now too :)

**Comment by GretaD** [comment]
I tested these and all looked good, but im not sure why i havent accepted the changes, will double check

**Review by st3iny — APPROVED** [review]
Makes the month view actually usable on mobile :+1:

**Pull request merged**
