### PR TITLE
remove Nextcloud 9 and 10 legacy code

### PR DESCRIPTION
**Pull request by georgehrke**
fixes https://github.com/nextcloud/calendar/issues/433

### CODE REVIEW

**Comment by georgehrke** [comment]
Todo:
- remove `<ocsid>168707</ocsid>` too

**Comment by georgehrke** [comment]
- [ ] add `stable12` and remove `stable9` and `stable10` from .travis.yml

**Comment by georgehrke** [comment]
@tcitworld Can we get this in? :) 

This also fixes compatibility with latest Nextcloud server master ;)

**Comment by tcitworld** [comment]
Tested and works properly, but I didn't check if there's more to remove.

**Comment by georgehrke** [comment]
thx for reviewing! :)

**Pull request merged**
