### PR TITLE
show email for attendee

### LINKED ISSUE #45: Attendee-Autocomplete: show e-mail address behind name
cc @schiessle

### PR DESCRIPTION
**Pull request by tcitworld**
I would like to have some `&hellip;` at the end when they're truncated, but `uib-typeahead` doesn't seem to accept ternaries directly, so I guess we need a full filter just for this.

Fixes #45

### CODE REVIEW

**Comment by raghunayyar** [comment]
:+1:

**Comment by jancborchardt** [comment]
@tcitworld is it maybe possible to ellipsize just using CSS and going with the width? Normal ellipsizing is achieved using:
```
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
```

**Comment by tcitworld** [comment]
I'll try.

**Comment by tcitworld** [comment]
Still the same issue on mobile, but at least it's okay on desktop view.

**Comment by raghunayyar** [comment]
@nextcloud/designers anyone up for a review? :)

**Comment by raghunayyar** [comment]
@georgehrke please review, its long pending. :)

**Comment by jancborchardt** [comment]
@raghunayyar can you post a quick screenshot?

**Comment by jancborchardt** [comment]
@raghunayyar can you post a quick screenshot?

**Comment by tcitworld** [comment]
@jancborchardt 
Desktop

Mobile

(Don't mind the display of the button, it's a Firefox Test Pilot issue)

**Comment by jancborchardt** [comment]
So as per the requirement in #45:

> otherwise a user is not able to distinguish which email address is used.

it’s only shown when a name is duplicate, right? Because normally it’s not necessary to show it. :)

And yeah, it would be good to get the ellipsizing down, should be possible by restricting the width of the input. cc @nextcloud/designers anyone wants to help out here? :)

**Comment by georgehrke** [comment]
@tcitworld Can you please only display the email address when there are multiple email addresses available for a user :)

**Comment by gqgunhed** [comment]
@georgehrke @tcitworld What about starting with the basic functionality as provided here and adding visual enhancements later on?
- showing email addresses only when contact has multiple email entries?
- maybe just showing the email domain part? (but that would collapse again in specific cases)
- select behavior via a setting switch in the calendar app?
Etc.
As most of my contact entries have multiple email addresses (work and home) it's very hard to figure out which is the correct name when setting up event invitations.
So thanks @tcitworld as I was searching for that functionality, but my JS/PHP skills are to bad ;-)

**Comment by georgehrke** [comment]
> maybe just showing the email domain part? (but that would collapse again in specific cases)

Then some emails will only have the domain and others will have the entire email address.
We should try to keep it consistent. Also I don't see a benefit in only showing the domain.

> select behavior via a setting switch in the calendar app?

I'm sorry, but this won't happen. We are trying to make things simple. Showing the email address when multiple are available and hiding it when only one is available covers all usecases.
Adding a setting doesn't solve anything imho and only clutters the user interface. :)

**Comment by georgehrke** [comment]
Changed the behavior to the expected one:

calendar - nextcloud chromium today at 1 44 03 pm

please review @jancborchardt @tcitworld @eppfel

**Comment by tcitworld** [comment]
Oh, I thought I had pushed the change.
LGTM 👍

**Comment by skjnldsv** [comment]
Are you using the select2 function? This should have the same design as tags, admin//workflow or other selects on nextcloud :)

**Comment by georgehrke** [comment]
Not yet.
Is there proper documentation on select2 and presumably select1/select?

**Comment by skjnldsv** [comment]
I don't know! 😞 
But systemtags is using it. https://select2.github.io

**Pull request merged**
