### PR TITLE
Fix disabled timezone

### LINKED ISSUE #4630: Cannot select timezone button
### Steps to reproduce

1. Start new calendar event
2. Deselect "All Day"
3. Set time
4. Try to select the globe icon to change the timezone

### Expected behavior

View pops up to modify the timezone

### Actual behaviour

Nothing happens. I cannot click on the globe icon

### Calendar app version

4.0.0

### CalDAV-clients used

_No response_

### Browser

Firefox 105.2, chromium 106.0.5249.103

### Client operating system

OpenBSD 7.2-current

### Server operating system

FreeBSD 13.1

### Web server

Nginx

### Database engine version

PostgreSQL

### PHP engine version

PHP 8.0

### Nextcloud version

25.0.0 RC5

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
- activity: 2.17.0                                                                                                                                                                           
  - admin_audit: 1.15.0                                                                                                                                                                        
  - apporder: 0.15.0                                                                                                                                                                           
  - bookmarks: 11.0.4                                                                                                                                                                          
  - bruteforcesettings: 2.5.0                                                                                                                                                                  
  - calendar: 4.0.0                                                                                                                                                                            
  - circles: 25.0.0-alpha.0                                                                                                                                                                    
  - cloud_federation_api: 1.8.0                                                                                                                                                                
  - comments: 1.15.0                                                                                                                                                                           
  - contacts: 5.0.0                                                                                                                                                                            
  - contactsinteraction: 1.6.0                                                                                                                                                                 
  - dashboard: 7.5.0                                                                                                                                                                           
  - dav: 1.24.0                                                                                                                                                                                
  - deck: 1.8.0-beta.2                                                                                                                                                                         
  - federatedfilesharing: 1.15.0                                                                                                                                                               
  - federation: 1.15.0                                                                                                                                                                         
  - files: 1.20.1                                                                                                                                                                              
  - files_accesscontrol: 1.15.0                                                                                                                                                                
  - files_automatedtagging: 1.15.0                                                                                                                                                             
  - files_downloadactivity: 1.15.0
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - groupfolders: 13.0.0
  - impersonate: 1.11.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - notify_push: 0.5.0
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - previewgenerator: 5.1.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quota_warning: 1.14.0
  - recommendations: 1.4.0
  - related_resources: 1.0.0
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - socialsharing_email: 2.5.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - tasks: 0.14.4
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - twofactor_webauthn: 1.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflow_pdf_converter: 1.10.0
  - workflowengine: 2.7.0
```

### Nextcloud configuration

_No response_

### Web server error log

_No response_

### Log file

_No response_

### Browser log

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by GretaD**
i spent one hour of my life trying to bisect this, just to realize that the popover component is changed.

- [x] Show the timezone list
- [ ] style it better

fixes #4630

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Should be backported

**Comment by ChristophWurst** [comment]
I clicked the merge button too early, didn't it?

**Comment by GretaD** [comment]
> I clicked the merge button too early, didn't it?

yes :), i will fix the styling right now, and backported it separately

**Pull request merged**
