### PR TITLE
"Appointment schedule" notion instead of only "Appointments" for a better UX

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
"Appointment" notion is no clear and creates confusion because this feature don't directly create an appointment but create an "appointment request form". I propose a new notion : "Appointment request form".
I made some wording change test with my browser dev tools. Please check below (real tests from reviewers are welcome) : 

Capture d’écran du 2024-09-25 11-40-30
Capture d’écran du 2024-09-25 11-41-37
Capture d’écran du 2024-09-25 11-48-00
Capture d’écran du 2024-09-25 11-51-43
Capture d’écran du 2024-09-25 11-52-29

### CODE REVIEW

**Review by nimishavijay — CHANGES_REQUESTED** [review]
This exact issue came up in a design review call! :) The discussion led to the conclusion that "Appointment schedule" is more appropriate. This is also on parity with Google Calendar (with uses the wording "Appointment schedule" to set this up) and Calendly (which calls itself an "Appointment scheduling software"). What do you think?

**Comment by Jerome-Herbinet** [comment]
> Appointment schedule

> This exact issue came up in a design review call! :) The discussion led to the conclusion that "Appointment schedule" is more appropriate. This is also on parity with Google Calendar (with uses the wording "Appointment schedule" to set this up) and Calendly (which calls itself an "Appointment scheduling software"). What do you think?

Thanks for your reply @nimishavijay ! Despite "Appointment request form" remains my favorite wording (personal preference), your suggestion is of course the best one because it fits wordings used by Google and it will make UX transition easier for end users. So, I'll make some new commits.

**Comment by Jerome-Herbinet** [comment]
@nimishavijay changes are done ; can you check and test it ?

**Review by nimishavijay — CHANGES_REQUESTED** [review]
Nice! Only a small change that I didn't notice before: "Appointment schedules" (plural form)

**Comment by Jerome-Herbinet** [comment]
> Nice! Only a small change that I didn't notice before: "Appointment schedules" (plural form)

Done @nimishavijay

**Review by nimishavijay — APPROVED** [review]

**Review by st3iny — APPROVED** [review]

**Pull request merged**
