### PR TITLE
Release 2.0.2

### PR DESCRIPTION
**Pull request by georgehrke**
Preparing the 2.0.2 release ...

I would still like to include the following in 2.0.2:
- [x] #2013 
- [x] #1929 
- [x] #1891 
- [x] #71 
- [x] update dependencies
- [x] https://github.com/nextcloud/calendar/pull/2042

### CODE REVIEW

**Comment by georgehrke** [comment]
@tcitworld Should we also address https://github.com/nextcloud/calendar/issues/577 by adding a simple select option for now to pick the slot height: Like: 10, 15, 20, 30 mins.

This was the second biggest issue we got negative feedback about after the "Show more"

**Comment by tcitworld** [comment]
> Should we also address #577 by adding a simple select option for now to pick the slot height: Like: 10, 15, 20, 30 mins.

We definitely should, yes. Maybe change back the default value as well, but I don't care much about this one.

At the same time I'm finding the Settings area getting too small for all of the settings, so if we add this option now we'll have to rethink how settings are handled (in a popup? move some options out of the app into general settings?). Can we work on this next?

**Comment by georgehrke** [comment]
> At the same time I'm finding the Settings area getting too small for all of the settings, so if we add this option now we'll have to rethink how settings are handled (in a popup? move some options out of the app into general settings?). Can we work on this next?

Definitely. Especially if we also add BusinessHours (for VAvailability in scheduling) and a UI for caldav proxy.

I think a popover will do fine.

**Comment by georgehrke** [comment]
Requires https://github.com/nextcloud/calendar/pull/2046

**Pull request merged**
