### PR TITLE
Fix busy for all overlap in free busy modal

### LINKED ISSUE #3135: Partly blocked free/busy slots spill to unrelated areas
For https://github.com/nextcloud/calendar/pull/2918 we improved the colors of the free/busy resources so that slots where at least one attendee is busy have a gray background, so they are easier to distinguish from slots that are free for all. There seems to be a flaw in that logic.

### Steps to reproduce
1. Create events with two attendees
2. Have some overlap but also section where only one person is busy

### Expected behaviour

Gray background only for slots where both attendees are busy.

### Actual behaviour

Bildschirmfoto von 2021-06-01 12-51-58

^ 08:30 to 9:00 should be gray for home office. The rest should be blocked or free.

### Calendar app
**Calendar app version:** 2.2.0+

### PR DESCRIPTION
**Pull request by st3iny**
Fixes #3135 

The overlap detection algorithm should work again now. I tried to catch all edge cases but this algorithm is kind of hard to get right.

Here is just one example which was broken before my patch:
Screenshot 2021-06-08 at 11-57-59 June 2021 - Calendar - Nextcloud

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Works perfectly now with the test data that previously showed wrong for me :+1: 

Awesome. One day we should write unit tests for this logic, it's too easy to get this wrong in a special case :wink:

**Comment by st3iny** [comment]
> Works perfectly now with the test data that previously showed wrong for me +1
> 
> Awesome. One day we should write unit tests for this logic, it's too easy to get this wrong in a special case wink

Agreed. We should definitely write some test for the combine method when we got some spare time.

**Comment by ChristophWurst** [comment]
Mind creating a simple ticket and tag as technical dep so we don't forget? :)

**Comment by st3iny** [comment]
Will do

**Pull request merged**
