### PR TITLE
Improve sidebar header layout

### PR DESCRIPTION
**Pull request by szaimen**
| Before | After |
|---|---|
| image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
As I said in https://github.com/nextcloud/tasks/pull/1700 this needs to be upstreamed.

**Comment by tcitworld** [comment]
Isn't that https://github.com/nextcloud/nextcloud-vue/pull/2054 ?

**Comment by szaimen** [comment]
> Isn't that [nextcloud/nextcloud-vue#2054](https://github.com/nextcloud/nextcloud-vue/pull/2054) ?

Looks like it, yes

**Pull request closed without merging**
