### PR TITLE
Fix freebusyUris naming inconsistencies

### PR DESCRIPTION
**Pull request by st3iny**
The name of the conflict calendar URIs field was inconsistent between the front and back end.

## How to test?

Create new and edit existing appointment configs and observe that conflict calendars are saved correctly.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:broom:

**Comment by ChristophWurst** [comment]
backport?

**Comment by st3iny** [comment]
> backport?

Makes sense! We should drop the bits in `AppointmentConfigModal` because the picker is not backported.

**Pull request merged**
