### PR TITLE
Use the color-primary-element* variables

### PR DESCRIPTION
**Pull request by szaimen**
Explanation: the color-primary variables are not to be used in components because the introduce problems with high-contrast primary colors. Fix this by using the primary-element variables instead.

### CODE REVIEW

**Comment by szaimen** [comment]
@skjnldsv do you know when they were introduced?

**Comment by ChristophWurst** [comment]
Use https://github.com/nextcloud/server/blob/master/core/css/variables.scss and the blame/history feature

**Comment by ChristophWurst** [comment]
Anything that exists in https://github.com/nextcloud/server/blob/stable25/core/css/variables.scss can be used here

**Comment by szaimen** [comment]
So it looks like they indeed can be used?

**Comment by ChristophWurst** [comment]
Did you find a declaration of `$color-primary-element-text` in 25?

**Comment by szaimen** [comment]
Yes: https://github.com/nextcloud/server/blob/stable25/apps/theming/css/default.css

**Comment by st3iny** [comment]
> Anything that exists in https://github.com/nextcloud/server/blob/stable25/core/css/variables.scss can be used here

It should be https://github.com/nextcloud/server/blob/stable25/apps/theming/css/default.css. The other file is SCSS variables (which are deprecated). We use CSS variables.

**Comment by st3iny** [comment]
But yeah, they all seem to be existing in stable25 so we are safe. 

I also checked occurrences and you caught them all.

**Review by st3iny — APPROVED** [review]

**Comment by st3iny** [comment]
A backport doesn't make sense as the new minor is around the corner and 24 is EOL. We will support >= 25 with the new minor.

**Pull request merged**
