### PR TITLE
Implement new Design for upper AppNavigation part

### LINKED ISSUE #1021: Simpler design for top part of navigation
The current top part of navigation has a bunch of actions which are rarely needed:

calendar nav before

This is a new proposal:
- A prominent (primary) "+ New event" button, which opens the event popover, by default a full-day event on _today_. Only this button has bold text.
- The "Today" button is put on the same line as it’s not soo important
- The day/week/month switcher is now just an icon indicating the current state. On click it opens a popover menu with a list of Day, Week, Month with the current one highlighted.

calendar navigation top new

cc @nextcloud/calendar 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/67813700-simpler-design-for-top-part-of-navigation?utm_campaign=plugin&utm_content=tracker%2F45525646&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F45525646&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #1021 

When you click "+ New event", it automatically opens the editor with a timed event set for today at the next full hour with a default length of one hour.

029982EB-2022-4B2B-A577-B09CBCF77991

DA438D65-304B-4DA3-8B44-5D2F597A55CD

92950D63-BAF6-4C33-9FC0-80D3906D9BB6

60FEE4AC-308B-4075-A8DB-FD089001748E

### CODE REVIEW

**Comment by jancborchardt** [comment]
Looks so much better, good stuff @georgehrke! :) Some notes:
- @tcitworld regarding your note on "Today" yeah, that’s a tough one. We could use the "Calendar icon which has the current date in it" but is that so understandable? Maybe worth to try it out.
- Since we have icons for all of "Day / Week / Month", maybe it makes more sense to use the currently active view as indicator of the switcher instead of the "Grid view" toggle icon. @skjnldsv noted the confusion of using the same icon in the past, and this could fix it?

**Comment by jancborchardt** [comment]
Another option is of course to put the "Today" entry out of the main view and inside the "Day / Week / Month" toggle as first entry. Then we can have the full text, but with the drawback that it’s not soo discoverable.

**Comment by georgehrke** [comment]
Let me replace Today with an icon and post a screenshot.
That will make it easier to discuss it :)

**Comment by georgehrke** [comment]
With button styles:
4F735354-336D-4129-BD5D-BFDFE0B32E81

Without:
B76BBCA4-5256-4D81-9E40-20AB1F0E7705

**Comment by skjnldsv** [comment]
> * @skjnldsv noted the confusion of using the same icon in the past, and this could fix it?

I'm afraid it looks even more confusing on the second screenshot :)
But I agree with the today icon :thinking: 

How does others calendar manage the view toggle icon?

**Comment by skjnldsv** [comment]
So, what about a dropdown with the current selected mode icon? :)
(and a triangle of course)

**Comment by jancborchardt** [comment]
I’d say for now what looks best of all of these is the current state of the pull request and @georgehrke’s screenshots above. It’s a big improvement on the current state.

So how about we merge it like this and look at the individual issues separately? :)

**Comment by jancborchardt** [comment]
> So, what about a dropdown with the current selected mode icon? :)

This is exactly what I suggested above ;)

**Comment by georgehrke** [comment]
D2E0E305-9039-463A-AC3F-826AB04817F5
0E53285D-53BA-49C2-9C60-9510A93FC1A2
1C55FE34-DE79-4158-BCE2-1D37AD3AD969

**Comment by georgehrke** [comment]
And since we use Flexbox now, the button automatically gets bigger:
A1BB7AC6-92B1-4B0B-A911-F02AC1BFC6C5

**Comment by georgehrke** [comment]
Not sure if that's the correct french translation, but then the button will have two lines:
F86DB4F5-56D7-41D5-873D-C0B1E5959126

**Comment by skjnldsv** [comment]
> Not sure if that's the correct french translation, but then the button will have two lines:

I'm guessing ellipsis would be good here.
It will take care of abbreviating long text. `Nouvel Evenem.`

**Comment by georgehrke** [comment]
C7DD62A4-9E8E-4A89-ABF3-1CB47495D23A

Let me push that

**Comment by skjnldsv** [comment]
Though it would be glad if we could ellipsis with one dot instead of 3! :p

**Comment by georgehrke** [comment]
Can you do that with CSS? I'm only aware of `text-overflow: ellipsis`, which does ...

**Comment by skjnldsv** [comment]
> Can you do that with CSS? I'm only aware of `text-overflow: ellipsis`, which does ...

I don't think so, not without hacks :(
https://stackoverflow.com/a/37594113

**Comment by georgehrke** [comment]
> https://stackoverflow.com/a/37594113

But this one shows ... even when nothing was truncated

**Comment by skjnldsv** [comment]
> But this one shows ... even when nothing was truncated

Yep, not really great :)
Let's move on! This is already an awesome improvement!

**Comment by tcitworld** [comment]
What about
```css
text-overflow: '.';
```

Also since the button's text translation is `+ New event` translators may choose to simple translate it into `+ Event` (and there's a smaller risk of using such a translation elsewhere).

**Comment by skjnldsv** [comment]
> ```css
> text-overflow: '.';
> ```

https://caniuse.com/#feat=mdn-css_properties_text-overflow_string

**Comment by tcitworld** [comment]
> https://caniuse.com/#feat=mdn-css_properties_text-overflow_string

Ouch, I thought I used this previously.

**Comment by georgehrke** [comment]
It's all so easy and straight forward with nextcloud/vue.  😍
The popover alone would have been a pain to implement in the old calendar.

**Comment by skjnldsv** [comment]
Glad you're enjoying it as well ! :rocket:

**Comment by jancborchardt** [comment]
> > ```css
> > text-overflow: '.';
> > ```
> 
> https://caniuse.com/#feat=mdn-css_properties_text-overflow_string

Let’s maybe not go with custom ellipsis though, no? One dot is not really obvious, and a bit confusing if it cuts it off mid-sentence with just a dot at the end of a sente.

**Pull request merged**
