### PR TITLE
fix(CalendarListNew): Public Calendar Modal Opening

### PR DESCRIPTION
**Pull request by SebastianKrupinski**
Resolves: https://github.com/nextcloud/calendar/issues/6341

### CODE REVIEW

**Comment by GVodyanov** [comment]
Told u ESLint wouldn't pass :P

**Review by GVodyanov — APPROVED** [review]

**Comment by SebastianKrupinski** [comment]
> Told u ESLint wouldn't pass :P

Lol. Yeah we both new this was the case.

**Pull request merged**
