### PR TITLE
Mathieu schopfer parsing schedule

### PR DESCRIPTION
**Pull request by georgehrke**
continuing the discussion here 

@MathieuSchopfer

### CODE REVIEW

**Comment by tcitworld** [comment]
@MathieuSchopfer Can you add a few tests ?

**Comment by MathieuSchopfer** [comment]
@tcitworld Sorry, what for tests ?
See this [fiddle](https://jsfiddle.net/MathieuSchopfer/0co07f8p/) for an equivalent example.

**Comment by tcitworld** [comment]
Test that entering `2:15-4:30 Title` correctly creates an event with the according title and correct times.

**Comment by MathieuSchopfer** [comment]
Oh ok, you want to automate the tests. I have to admit, I have never done it before.
Where should they be located (I guess calendar/tests/js/unit/controllers/) ? And how do you actually run them?

**Comment by tcitworld** [comment]
In fact I think it would be better to have this code as a service. cc @georgehrke

**Comment by georgehrke** [comment]
This pull-request lacks support for different locales, which will definitely not be an easy task to implement.

Closing in favour of https://github.com/nextcloud/calendar/issues/17 for now.

**Pull request closed without merging**
