### PR TITLE
Improve handling of email alarms

### LINKED ISSUE #4671: Extend the `VALARM` property to include `ATTENDEE` and `SUMMARY` properties when `ACTION:EMAIL`
### Is your feature request related to a problem? Please describe.

Currently, we send duplicate reminder emails to all `ATTENDEEs` of a `VEVENT`. To improve this, we should implement `VALARMs` with `ATTENDEEs` as descibed in the [RFC](https://www.rfc-editor.org/rfc/rfc5545#section-3.6.6).

### Describe the solution you'd like

The new VALARM property for email reminders should look like this

```ics
BEGIN:VALARM
ACTION:EMAIL
DESCRIPTION:This is an event reminder
SUMMARY:Alarm notification
ATTENDEE:mailto:xxxxxxx@gmail.com
TRIGGER:-P0DT2H0M0S
END:VALARM
```

The second item MUST have a summary, which can be the `VEVENT` summary.

Extend the current calendar object creation to allow setting the `EMAIL` notification for `ATTENDEE`s. This can or cannot include the `ORGANIZER`. We currently don't support defering the attendance of the `ORGANIZER` to somebody else, so they should be added to the `VALARM`.

### Describe alternatives you've considered

--

### Additional context

https://github.com/nextcloud/server/issues/21370

### PR DESCRIPTION
**Pull request by st3iny**
Fix #4671 #4490

### CODE REVIEW

**Review by tcitworld — COMMENTED** [review]
> When the action is "EMAIL", the alarm MUST include a "DESCRIPTION" property, which contains the text to be used as the message body, a "SUMMARY" property, which contains the text to be used as the message subject

Not saying we should use it to send emails, but I don't think the DESCRIPTION property should match the event description. Some generic translated sentence could do it (« don't forget to go to X »…)

**Comment by st3iny** [comment]
> > When the action is "EMAIL", the alarm MUST include a "DESCRIPTION" property, which contains the text to be used as the message body, a "SUMMARY" property, which contains the text to be used as the message subject
> 
> Not saying we should use it to send emails, but I don't think the DESCRIPTION property should match the event description. Some generic translated sentence could do it (« don't forget to go to X »…)

To be honest, we could just use a generic placeholder for both (just like Google does). The values aren't used anyways because the server generates a notification email from a template.

If an event is shared, the other backend won't send notifications because only the backend of the organizer should send emails. So, the content provides no value for other implementations either.

**Comment by tcitworld** [comment]
> the other backend won't send notifications because only the backend of the organizer should send emails

Well the organizer can use different different backends at the same time. :)

But yes, it's just about the values making minimal sense. The event's title for SUMMARY made sense to me, placeholder can work for DESCRIPTION.

**Review by miaulalala — APPROVED** [review]
LGTM!

**Pull request merged**
