### PR TITLE
Fix for overlapping datepicker.

### PR DESCRIPTION
**Pull request by raghunayyar**
Fixes: https://github.com/nextcloud/calendar/issues/85

This is an urgent fix, lets get this in asap @georgehrke @nextcloud/calendar

### CODE REVIEW

**Comment by georgehrke** [comment]
breaks scroll ability again 👎

**Comment by georgehrke** [comment]
@raimund-schluessler 's suggestion probably helps here
https://github.com/nextcloud/calendar/pull/75#issuecomment-248577541

**Comment by tcitworld** [comment]
@raghunayyar Any news ?

**Comment by georgehrke** [comment]
@raghunayyar Are you up for a proper fix or do you want someone else to take a look?

**Comment by skjnldsv** [comment]
Here is my suggestion. What do you think?
@raghunayyar if you don't want to do like me, trow away my commit ;)

**Comment by tcitworld** [comment]
Looks good. The transition is not perfect on Firefox (good on Chromium), but it seems quite fine apart from this.

**Comment by skjnldsv** [comment]
We can remove it entirely if we want. It's not really essential :)

**Comment by georgehrke** [comment]
@skjnldsv Is something missing in your latest commit?
I tried with latest chromium and latest firefox on os x yosemite
(Yes, I ran `grunt build` and chromium/firefox also load the latest version 😉)

**Comment by skjnldsv** [comment]
@georgehrke Yes there is indeed! I failed my rebase. Wait a sec!

**Comment by skjnldsv** [comment]
@georgehrke done! Thanks for noticing!

**Comment by georgehrke** [comment]
Thx! testing now ...

```
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 16 (delta 6), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), done.
From github.com:nextcloud/calendar
   802c5dc..905aca7  bugfix/overlapping-datepicker        -> origin/bugfix/overlapping-datepicker
 * [new branch]      origin/bugfix/overlapping-datepicker -> origin/origin/bugfix/overlapping-datepicker
Already up-to-date.
```

Can I delete `origin/bugfix/overlapping-datepicker`? ;)

**Comment by skjnldsv** [comment]
Lol, that explains the failed rebase :D 
yes you can 😆

**Comment by raghunayyar** [comment]
Appreciate the help here gentlemen. ;)

**Comment by georgehrke** [comment]
Please don't merge yet, I won't to try something

**Comment by georgehrke** [comment]
I added a slide down transition for the date picker.
please check @skjnldsv @raghunayyar @tcitworld :)

**Comment by tcitworld** [comment]
Works flawlessly ! :+1:

**Comment by skjnldsv** [comment]
This is perfect! 👍

**Pull request merged**
