### PR TITLE
Fix Datepicker localization

### LINKED ISSUE #2174: Date picker is not localized
### Steps to reproduce
1. Click date picker (which is localized correctly in long format)
2. See that the monthly calendar picker uses English short forms, ie Jan, Feb, Mar, Apr, May, ...

### Expected behaviour
When picking a date in month popup it should show the date in user's locale.

### Actual behaviour
The popup shows the month in English. This example shows Swedish in top (correctly localized), and English below (incorrect):
datepicker

### Calendar app
**Calendar app version:** 2.0.3

**CalDAV-clients used:** N/A

### Client configuration
**Browser:** Firefox 74

**Operating system:** Ubuntu

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud Version:** 17.0.5

**Updated from an older installed version or fresh install:**
Update.

#### Web server error log (e.g. /var/log/apache)
No error.

#### Log file (data/nextcloud.log)
No error.

#### Browser log
```
Content Security Policy: Sidans inställningar blockerade laddningen av en resurs på inline (“script-src”). 2 utils.js:35:9
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
oc_config is deprecated: use OC.config instead globals.js:26:15
Denna sida använder den icke-standardegenskapen “zoom”. Överväg att använda calc() i relevanta egenskapsvärden eller använd “transform” tillsammans med “transform-origin: 0 0”. injectStylesIntoStyleTag.js:201:10
Proxying an event bus of version 0.2.1 with 1.1.4 ProxyBus.js:72:14
Initial settings: 
Object { appVersion: "2.0.3", eventLimit: true, firstRun: false, showWeekends: true, showWeekNumbers: true, skipPopover: false, slotDuration: "00:30:00", talkEnabled: false, timezone: "automatic" }
settings.js:109:2
[DEBUG] calendar: The calendar app is using version 2.2019c of the timezone database 
Object { app: "calendar", uid: "authenticated:hans" }
ConsoleLogger.js:42:18
The escapeHTML library is deprecated! It will be removed in nextcloud 19. globals.js:26:15
[DEBUG] calendar: Current user principal is /remote.php/dav/principals/users/hans/ 
Object { app: "calendar", uid: "authenticated:hans" }
ConsoleLogger.js:42:18
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 2 globals.js:26:15

```

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #2174

fixes first day of week
fixes title of month in header

| Before | After |
|:---------:|:------:|
|datepicker_before|6C199988-3F02-4778-BEB6-A6E8C03DC456|

### CODE REVIEW

**Comment by georgehrke** [comment]
`src/utils/localization.js` still needs some tests, once i added them this is ready to test.

**Comment by tcitworld** [comment]
Didn't have a look yet but from the screenshot short day of week names are not localized.

**Comment by georgehrke** [comment]
> Didn't have a look yet but from the screenshot short day of week names are not localized.

The days names in the screenshot are correctly localised in german:
(Mo)ntag (Di)enstag (Mi)ttwoch ...

**Comment by tcitworld** [comment]
I thought that was French. :p

**Comment by dnv** [comment]
Is this getting fixed? My Nextcloud locale is set to English (Finland) with Week starts on Monday clearly shown under Settings, yet the Calendar week starts on Sunday when opened via web browser.

**Comment by tcitworld** [comment]
@dnv See #2663

**Pull request merged**
